// typeship — account resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import { TransportError, UnexpectedApiError, ValidationError, UnauthorizedError } from "../errors.js";
import type { Account } from "../types.js";

export class AccountResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * The account behind the presented credentials
   * 
   * Returns the account that owns the presented API key. This is also the
   * identity endpoint the generated typeship CLI's `whoami` calls.
   * `GET /me`
   */
  async me(options?: RequestOptions): Promise<ApiResult<Account, AccountMeError>> {
    return this._core.request<Account, AccountMeError>({
      method: "GET",
      path: "/me",
      errors: { "401": UnauthorizedError },
      idempotent: true,
      schemaKey: "account.me",
      options,
    });
  }
}

/** Every error `me` can produce, as a discriminated union. */
export type AccountMeError = UnauthorizedError | UnexpectedApiError | TransportError | ValidationError;

