// typeship — account resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import {
  ResponseParseError,
  TransportError,
  UnexpectedApiError,
  ValidationError,
  ForbiddenError,
  InternalServerError,
  RateLimitedError,
  UnauthorizedError,
} from "../errors.js";
import type { Account, AccountRead } from "../types.js";

export class AccountResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * The account behind the presented credentials
   *
   * Returns the account associated with your credential. The Typeship CLI uses this endpoint for
   * `whoami`.
   * `GET /me`
   */
  async retrieve(options?: RequestOptions): Promise<ApiResult<AccountRead, AccountRetrieveError>> {
    return this._core.request<AccountRead, AccountRetrieveError>({
      method: "GET",
      path: "/me",
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "account.retrieve",
      options,
    });
  }
}

/** Every error `retrieve` can produce, as a discriminated union. */
export type AccountRetrieveError =
  | UnauthorizedError
  | ForbiddenError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;
