// typeship — account resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import { TransportError, UnexpectedApiError, ValidationError, ForbiddenError, RateLimitedError, UnauthorizedError } from "../errors.js";
import type { Account } from "../types.js";

export class AccountResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * The account behind the presented credentials
   *
   * Returns the account that owns the presented API key. This is also the
   * identity endpoint the generated typeship CLI's `whoami` calls.
   * `GET /me`
   */
  async retrieve(options?: RequestOptions): Promise<ApiResult<Account, AccountRetrieveError>> {
    return this._core.request<Account, AccountRetrieveError>({
      method: "GET",
      path: "/me",
      errors: { "401": UnauthorizedError, "403": ForbiddenError, "429": RateLimitedError },
      idempotent: true,
      schemaKey: "account.retrieve",
      options,
    });
  }
}

/** Every error `retrieve` can produce, as a discriminated union. */
export type AccountRetrieveError = UnauthorizedError | ForbiddenError | RateLimitedError | UnexpectedApiError | TransportError | ValidationError;
