// typeship — apiKeys resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import { paginate, PagePromise } from "../core/pagination.js";
import {
  TransportError,
  UnexpectedApiError,
  ValidationError,
  BadRequestError,
  ForbiddenError,
  NotFoundError,
  RateLimitedError,
  UnauthorizedError,
} from "../errors.js";
import type {
  ApiKey,
  ApiKeyList,
  ApiKeyListRead,
  ApiKeyRead,
  ApiKeyResponse,
  ApiKeyResponseRead,
} from "../types.js";

export class ApiKeysResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * List API keys
   *
   * Keys are never returned in full — only their identity and last four. Creation stays in the
   * console deliberately: a leaked key that can mint more keys is a leaked account.
   *
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /api_keys`
   */
  list(params?: ApiKeysListParams, options?: RequestOptions): PagePromise<ApiKeyRead, ApiKeysListError> {
    return paginate<ApiKeyRead, ApiKeysListError>(this._core, {
      method: "GET",
      path: "/api_keys",
      query: {
        limit: params?.limit,
        cursor: params?.cursor,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "429": RateLimitedError,
      },
      idempotent: true,
      schemaKey: "apiKeys.list",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      hasMoreField: "has_more",
      limitParam: "limit",
    });
  }

  /**
   * Revoke an API key
   *
   * Idempotent: revoking an already-revoked key returns the same body, so a rotation script that
   * re-runs does not have to special-case having already succeeded. An OAuth member may revoke a
   * key they created; an organization admin may revoke any key. Organization API keys retain
   * account-wide authority.
   * `DELETE /api_keys/{api_key_id}`
   */
  async revoke(
    apiKeyId: string,
    options?: RequestOptions,
  ): Promise<ApiResult<ApiKeyResponseRead, ApiKeysRevokeError>> {
    return this._core.request<ApiKeyResponseRead, ApiKeysRevokeError>({
      method: "DELETE",
      path: `/api_keys/${encodeURIComponent(String(apiKeyId))}`,
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
      },
      idempotent: true,
      schemaKey: "apiKeys.revoke",
      options,
    });
  }
}

export interface ApiKeysListParams {
  /** Maximum number of resources to return. */
  limit?: number;
  /**
   * Opaque cursor from the preceding page's next_cursor. Valid only for the same account,
   * operation, filters, and ordering that issued it.
   */
  cursor?: string;
}

/** Every error `list` can produce, as a discriminated union. */
export type ApiKeysListError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | RateLimitedError
  | UnexpectedApiError
  | TransportError
  | ValidationError;

/** Every error `revoke` can produce, as a discriminated union. */
export type ApiKeysRevokeError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | UnexpectedApiError
  | TransportError
  | ValidationError;
