// typeship — generate resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import { TransportError, UnexpectedApiError, ValidationError, ApiResponseError, PayloadTooLargeError, UnprocessableEntityError } from "../errors.js";
import type { Config, GenerationResult, SpecInput } from "../types.js";

export class GenerateResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * Generate a package from a spec
   * 
   * Stateless generation, no authentication. Nothing is stored. Returns
   * the full generated package as files.
   * `POST /generate`
   */
  async run(body: {
    spec: SpecInput;
    /** Artifacts to generate from the spec. Defaults to [sdk]. */
    platforms?: Array<"sdk" | "cli" | "mcp" | "agent">;
    /**
     * Language to generate. Python and Go produce the SDK only; the CLI, MCP server, and agent context are TypeScript artifacts and are skipped with a warning when requested alongside them.
     * Default: "typescript"
     */
    language?: "typescript" | "python" | "go";
    /** npm name override for the generated package. */
    package_name?: string;
    config?: Config;
  }, options?: RequestOptions): Promise<ApiResult<GenerationResult, GenerateRunError>> {
    return this._core.request<GenerationResult, GenerateRunError>({
      method: "POST",
      path: "/generate",
      body,
      errors: { "413": PayloadTooLargeError, "422": UnprocessableEntityError, default: ApiResponseError },
      schemaKey: "generate.run",
      options,
    });
  }
}

/** Every error `run` can produce, as a discriminated union. */
export type GenerateRunError = PayloadTooLargeError | UnprocessableEntityError | ApiResponseError | UnexpectedApiError | TransportError | ValidationError;

