// typeship — generations resource.
// Generated by typeship — https://typeship.dev

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import {
  ResponseParseError,
  TransportError,
  UnexpectedApiError,
  ValidationError,
  BadRequestError,
  ForbiddenError,
  InternalServerError,
  NotFoundError,
  RateLimitedError,
  UnauthorizedError,
} from "../errors.js";
import type { GenerationId, GenerationResponse, GenerationResponseRead } from "../types.js";

export class GenerationsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * Retrieve a generation
   *
   * Returns the Generation result. Successful results include files, or a file index when the
   * package is too large to inline.
   * `GET /generations/{generation_id}`
   */
  async retrieve(
    generationId: GenerationId,
    options?: RequestOptions,
  ): Promise<ApiResult<GenerationResponseRead, GenerationsRetrieveError>> {
    return this._core.request<GenerationResponseRead, GenerationsRetrieveError>({
      method: "GET",
      path: `/generations/${encodeURIComponent(String(generationId))}`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "generations.retrieve",
      options,
    });
  }

  /**
   * Fetch one file from a generation
   *
   * Returns one file's raw content. Use a path from `files_index` when the Generation reports
   * `files_omitted: true`.
   * `GET /generations/{generation_id}/file`
   */
  async retrieveFile(
    generationId: GenerationId,
    params: GenerationsRetrieveFileParams,
    options?: RequestOptions,
  ): Promise<ApiResult<string, GenerationsRetrieveFileError>> {
    return this._core.request<string, GenerationsRetrieveFileError>({
      method: "GET",
      path: `/generations/${encodeURIComponent(String(generationId))}/file`,
      security: [{"apiKey":[]}],
      query: {
        path: params.path,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "generations.retrieveFile",
      options,
    });
  }
}

/** Every error `retrieve` can produce, as a discriminated union. */
export type GenerationsRetrieveError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface GenerationsRetrieveFileParams {
  /** Repo-relative path inside the generated package. */
  path: string;
}

/** Every error `retrieveFile` can produce, as a discriminated union. */
export type GenerationsRetrieveFileError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;
