// typeship — generations resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import { TransportError, UnexpectedApiError, ValidationError, NotFoundError, UnauthorizedError } from "../errors.js";
import type { Generation } from "../types.js";

export class GenerationsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * Retrieve a generation
   *
   * Includes the generated files when the generation succeeded.
   * `GET /generations/{generation_id}`
   */
  async get(generationId: string, options?: RequestOptions): Promise<ApiResult<Generation, GenerationsGetError>> {
    return this._core.request<Generation, GenerationsGetError>({
      method: "GET",
      path: `/generations/${encodeURIComponent(String(generationId))}`,
      errors: { "401": UnauthorizedError, "404": NotFoundError },
      idempotent: true,
      schemaKey: "generations.get",
      options,
    });
  }

  /**
   * Fetch one file from a generation
   *
   * Raw file content, for generations whose output was too large to inline (files_omitted true). The generation's files_index lists valid paths.
   * `GET /generations/{generation_id}/file`
   */
  async getFile(generationId: string, params: GenerationsGetFileParams, options?: RequestOptions): Promise<ApiResult<string, GenerationsGetFileError>> {
    return this._core.request<string, GenerationsGetFileError>({
      method: "GET",
      path: `/generations/${encodeURIComponent(String(generationId))}/file`,
      query: { path: params.path },
      errors: { "401": UnauthorizedError, "404": NotFoundError },
      idempotent: true,
      schemaKey: "generations.getFile",
      options,
    });
  }
}

/** Every error `get` can produce, as a discriminated union. */
export type GenerationsGetError = UnauthorizedError | NotFoundError | UnexpectedApiError | TransportError | ValidationError;

export interface GenerationsGetFileParams {
  /** Repo-relative path inside the generated package. */
  path: string;
}

/** Every error `getFile` can produce, as a discriminated union. */
export type GenerationsGetFileError = UnauthorizedError | NotFoundError | UnexpectedApiError | TransportError | ValidationError;

