// typeship — generations resource.
// Generated by typeship — https://typeship.dev

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import {
  ResponseParseError,
  TransportError,
  UnexpectedApiError,
  ValidationError,
  BadRequestError,
  ForbiddenError,
  InternalServerError,
  NotFoundError,
  RateLimitedError,
  UnauthorizedError,
} from "../errors.js";
import type { GenerationId, GenerationResponse, GenerationResponseRead } from "../types.js";

export class GenerationsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * Retrieve a generation
   *
   * Returns the current Generation status. `queued` and `running` mean generation is still in
   * progress. `succeeded` means generated files are saved, not that repository delivery or a Draft
   * is complete. Successful results include files, or a file index when the package is too large to
   * inline.
   * `GET /generations/{generation_id}`
   */
  async retrieve(
    generationId: GenerationId,
    options?: RequestOptions,
  ): Promise<ApiResult<GenerationResponseRead, GenerationsRetrieveError>> {
    return this._core.request<GenerationResponseRead, GenerationsRetrieveError>({
      method: "GET",
      path: `/generations/${encodeURIComponent(String(generationId))}`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "generations.retrieve",
      options,
    });
  }

  /**
   * Fetch one file from a generation
   *
   * Returns one file's raw content. Use a path from `files_index` when the Generation reports
   * `files_omitted: true`.
   * `GET /generations/{generation_id}/file`
   */
  async retrieveFile(
    generationId: GenerationId,
    params: GenerationsRetrieveFileParams,
    options?: RequestOptions,
  ): Promise<ApiResult<string, GenerationsRetrieveFileError>> {
    return this._core.request<string, GenerationsRetrieveFileError>({
      method: "GET",
      path: `/generations/${encodeURIComponent(String(generationId))}/file`,
      security: [{"apiKey":[]}],
      query: {
        path: params.path,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "generations.retrieveFile",
      options,
    });
  }

/** Poll until files are generated or the Generation fails. */
  async wait(
    generationId: GenerationId,
    options: RequestOptions & { intervalMs?: number; waitTimeoutMs?: number } = {},
  ): Promise<ApiResult<GenerationResponseRead, GenerationsRetrieveError>> {
    const { intervalMs = 1_000, waitTimeoutMs = 600_000, ...requestOptions } = options;
    const deadline = Date.now() + waitTimeoutMs;
    while (true) {
      if (requestOptions.signal?.aborted) {
        throw requestOptions.signal.reason ?? new Error("Generation wait aborted.");
      }
      const result = await this.retrieve(generationId, requestOptions);
      if (!result.ok || (result.data.status !== "queued" && result.data.status !== "running")) return result;
      if (Date.now() >= deadline) throw new Error("Timed out waiting for Generation " + generationId + ".");
      await new Promise<void>((resolve) =>
        setTimeout(resolve, Math.min(intervalMs, deadline - Date.now())));
    }
  }
}

/** Every error `retrieve` can produce, as a discriminated union. */
export type GenerationsRetrieveError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface GenerationsRetrieveFileParams {
  /** Repo-relative path inside the generated package. */
  path: string;
}

/** Every error `retrieveFile` can produce, as a discriminated union. */
export type GenerationsRetrieveFileError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;
