// typeship — generate resource.
// Generated by typeship — https://typeship.dev

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import {
  ResponseParseError,
  TransportError,
  UnexpectedApiError,
  ValidationError,
  ApiResponseError,
  BadRequestError,
  ConflictError,
  ForbiddenError,
  InternalServerError,
  NotFoundError,
  PayloadTooLargeError,
  RateLimitedError,
  UnauthorizedError,
  UnprocessableEntityError,
} from "../errors.js";
import type { GenerateRequest, GenerationResult, GenerationResultRead } from "../types.js";

export class GenerateResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * Generate one package from a Definition
   *
   * Returns one generated package without creating a Project.
   *
   * Supports [idempotent retries](https://typeship.dev/docs/typeship-api/idempotency); keyed
   * responses include generated files in the replay cache.
   *
   * Use `download.url` to save the complete ZIP, verify `download.sha256`, and extract it into an
   * empty directory. The link expires at `download.expires_at` and grants access to anyone who has
   * it. CLI, MCP, and SDK calls supply an idempotency key automatically. Agents should request
   * `fields=["download","meta","warnings","limits","claim"]` to keep the MCP result compact; files
   * can exceed the response limit. Download the ZIP instead of repeating generation to retrieve
   * omitted files.
   *
   * Anonymous and Free requests include the first 25 operations. Paid plans include all operations.
   * Anonymous requests are rate limited by IP address. Check `limits` for omitted operations; an
   * invalid API key returns `401`.
   *
   * An anonymous URL request without source headers may return `claim.url`. Sign in through that
   * link within seven days to save the recipe as a Project.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `POST /generate`
   */
  async run(
    body: GenerateRequest,
    params?: GenerateRunParams,
    options?: RequestOptions,
  ): Promise<ApiResult<GenerationResultRead, GenerateRunError>> {
    return this._core.request<GenerationResultRead, GenerateRunError>({
      method: "POST",
      path: "/generate",
      security: [{},{"apiKey":[]}],
      headers: {
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "409": ConflictError,
        "413": PayloadTooLargeError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
        default: ApiResponseError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "generate.run",
      options,
    });
  }

  /**
   * Download a generated package
   *
   * Download the complete ZIP referenced by `generate_run`'s `download.url`. Pass the token from
   * that URL. No API key is needed; the token grants access only to that exact package until its
   * replay window expires. Keep the token private.
   *
   * The local MCP server saves this binary response to disk. On a hosted MCP connection, download
   * the original URL directly to your workspace. Verify the ZIP against `download.sha256` before
   * extracting it into an empty directory. Expired or invalid tokens return `404`; a new generation
   * creates a new download.
   * `GET /generate/download`
   */
  async downloadPackage(
    params: GenerateDownloadPackageParams,
    options?: RequestOptions,
  ): Promise<ApiResult<Blob, GenerateDownloadPackageError>> {
    return this._core.request<Blob, GenerateDownloadPackageError>({
      method: "GET",
      path: "/generate/download",
      security: [{}],
      query: {
        token: params.token,
      },
      errors: {
        "400": BadRequestError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "generate.downloadPackage",
      options,
    });
  }
}

export interface GenerateRunParams {
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated account and
   * operation; account-less generation uses a hashed network identity. Retrying the same method,
   * path, query, and JSON body replays the original response. Reusing the key with changed intent
   * returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Every error `run` can produce, as a discriminated union. */
export type GenerateRunError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | ConflictError
  | PayloadTooLargeError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | ApiResponseError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface GenerateDownloadPackageParams {
  /** Private download token from download.url in the generation result. */
  token: string;
}

/** Every error `downloadPackage` can produce, as a discriminated union. */
export type GenerateDownloadPackageError =
  | BadRequestError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;
