// typeship — projects resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import { paginate, PagePromise } from "../core/pagination.js";
import { TransportError, UnexpectedApiError, ValidationError, BadRequestError, NotFoundError, PaymentRequiredError, UnauthorizedError, UnprocessableEntityError } from "../errors.js";
import type {
  Config,
  Destination,
  Generation,
  GenerationFailure,
  Project,
  Source,
  SpecPatch,
} from "../types.js";

export class ProjectsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * List projects
   * 
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /projects`
   */
  list(params?: ProjectsListParams, options?: RequestOptions): PagePromise<Project, ProjectsListError> {
    return paginate<Project, ProjectsListError>(this._core, {
      method: "GET",
      path: "/projects",
      query: { limit: params?.limit, cursor: params?.cursor },
      errors: { "401": UnauthorizedError },
      idempotent: true,
      schemaKey: "projects.list",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      limitParam: "limit",
    });
  }

  /**
   * Create a project
   * `POST /projects`
   */
  async create(body: {
    name: string;
    /** Spec location for a URL-sourced project. Provide this or source; a project with neither has nothing to generate. */
    spec_url?: string;
    source?: Source;
    /** Artifacts to build. sdk is implied; cli, mcp, and agent require typescript among the languages. Free projects run one platform in total (one SDK language); more is a 402 until the account is on Pro. */
    platforms?: Array<"sdk" | "cli" | "mcp" | "agent">;
    /** Languages to generate. Each is a separate package, a separate pull request, a separate hosted generation, and one platform for billing. Defaults to typescript alone. */
    languages?: Array<"typescript" | "python" | "go">;
    /** Per-language pull-request destination, keyed by language. */
    destinations?: Record<string, Destination>;
    /** Registry name per language; unset derives from the API title. */
    package_names?: Record<string, string>;
    destination?: Destination | null;
    auto_regen?: boolean;
    package_name?: string | null;
    spec_patches?: SpecPatch[];
    /** Requires the mcp platform and Pro. */
    mcp_enabled?: boolean;
    /** Requires the cli platform and Pro. */
    relay_enabled?: boolean;
    /** Requires the agent platform and Pro. */
    agent_context_enabled?: boolean;
    config?: Config | null;
  }, options?: RequestOptions): Promise<ApiResult<Project, ProjectsCreateError>> {
    return this._core.request<Project, ProjectsCreateError>({
      method: "POST",
      path: "/projects",
      body,
      errors: { "400": BadRequestError, "401": UnauthorizedError, "402": PaymentRequiredError },
      schemaKey: "projects.create",
      options,
    });
  }

  /**
   * Retrieve a project
   * `GET /projects/{project_id}`
   */
  async get(projectId: string, options?: RequestOptions): Promise<ApiResult<Project, ProjectsGetError>> {
    return this._core.request<Project, ProjectsGetError>({
      method: "GET",
      path: `/projects/${encodeURIComponent(String(projectId))}`,
      errors: { "401": UnauthorizedError, "404": NotFoundError },
      idempotent: true,
      schemaKey: "projects.get",
      options,
    });
  }

  /**
   * Delete a project
   * `DELETE /projects/{project_id}`
   */
  async delete(projectId: string, options?: RequestOptions): Promise<ApiResult<{
    deleted: true;
  }, ProjectsDeleteError>> {
    return this._core.request<{
    deleted: true;
  }, ProjectsDeleteError>({
      method: "DELETE",
      path: `/projects/${encodeURIComponent(String(projectId))}`,
      errors: { "401": UnauthorizedError, "404": NotFoundError },
      idempotent: true,
      schemaKey: "projects.delete",
      options,
    });
  }

  /**
   * Update a project
   * `PATCH /projects/{project_id}`
   */
  async update(projectId: string, body: {
    name?: string;
    spec_url?: string;
    source?: Source;
    /** Artifacts to build; replaces the list. Dropping cli, mcp, or agent turns off the hosted feature it serves. cli, mcp, and agent require typescript among the languages. Turning a platform off stops generating it; nothing already delivered is removed. */
    platforms?: Array<"sdk" | "cli" | "mcp" | "agent">;
    destination?: Destination | null;
    /** Languages to generate; replaces the list. Each is its own hosted generation and one platform for billing. */
    languages?: Array<"typescript" | "python" | "go">;
    /** Per-language pull-request destination, keyed by language. */
    destinations?: Record<string, Destination>;
    /** Registry name per language; unset derives from the API title. */
    package_names?: Record<string, string>;
    auto_regen?: boolean;
    package_name?: string | null;
    spec_patches?: SpecPatch[];
    /** Serve this project as a hosted remote MCP endpoint. Requires the mcp platform and Pro. */
    mcp_enabled?: boolean;
    /** Enable the webhook relay so the generated CLI's webhooks listen command works for this API's users. Requires the cli platform and Pro. */
    relay_enabled?: boolean;
    /** Serve an always-current AGENTS.md for this API at a stable hosted URL. Requires the agent platform and Pro. */
    agent_context_enabled?: boolean;
    /** Replaces the whole config. Pass null to clear it. */
    config?: Config | null;
  }, options?: RequestOptions): Promise<ApiResult<Project, ProjectsUpdateError>> {
    return this._core.request<Project, ProjectsUpdateError>({
      method: "PATCH",
      path: `/projects/${encodeURIComponent(String(projectId))}`,
      body,
      errors: { "400": BadRequestError, "401": UnauthorizedError, "402": PaymentRequiredError, "404": NotFoundError },
      schemaKey: "projects.update",
      options,
    });
  }

  /**
   * List a project's generations
   * 
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /projects/{project_id}/generations`
   */
  listGenerations(projectId: string, params?: ProjectsListGenerationsParams, options?: RequestOptions): PagePromise<Generation, ProjectsListGenerationsError> {
    return paginate<Generation, ProjectsListGenerationsError>(this._core, {
      method: "GET",
      path: `/projects/${encodeURIComponent(String(projectId))}/generations`,
      query: { limit: params?.limit, cursor: params?.cursor, language: params?.language },
      errors: { "401": UnauthorizedError, "404": NotFoundError },
      idempotent: true,
      schemaKey: "projects.listGenerations",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      limitParam: "limit",
    });
  }

  /**
   * Run a hosted generation
   * 
   * Fetches the project's spec URL, generates every configured language,
   * and stores each result in the project's history. Each language
   * counts as one hosted generation. Does not open pull requests. Only
   * URL-sourced projects can be regenerated this way; repository sources
   * regenerate on push.
   * `POST /projects/{project_id}/generations`
   */
  async generate(projectId: string, options?: RequestOptions): Promise<ApiResult<{
    data: Array<Generation | GenerationFailure>;
  }, ProjectsGenerateError>> {
    return this._core.request<{
    data: Array<Generation | GenerationFailure>;
  }, ProjectsGenerateError>({
      method: "POST",
      path: `/projects/${encodeURIComponent(String(projectId))}/generations`,
      errors: { "401": UnauthorizedError, "402": PaymentRequiredError, "404": NotFoundError, "422": UnprocessableEntityError },
      schemaKey: "projects.generate",
      options,
    });
  }
}

export interface ProjectsListParams {
  limit?: number;
  cursor?: string;
}

/** Every error `list` can produce, as a discriminated union. */
export type ProjectsListError = UnauthorizedError | UnexpectedApiError | TransportError | ValidationError;

/** Every error `create` can produce, as a discriminated union. */
export type ProjectsCreateError = BadRequestError | UnauthorizedError | PaymentRequiredError | UnexpectedApiError | TransportError | ValidationError;

/** Every error `get` can produce, as a discriminated union. */
export type ProjectsGetError = UnauthorizedError | NotFoundError | UnexpectedApiError | TransportError | ValidationError;

/** Every error `delete` can produce, as a discriminated union. */
export type ProjectsDeleteError = UnauthorizedError | NotFoundError | UnexpectedApiError | TransportError | ValidationError;

/** Every error `update` can produce, as a discriminated union. */
export type ProjectsUpdateError = BadRequestError | UnauthorizedError | PaymentRequiredError | NotFoundError | UnexpectedApiError | TransportError | ValidationError;

export interface ProjectsListGenerationsParams {
  limit?: number;
  cursor?: string;
  /** Only generations for this language. */
  language?: "typescript" | "python" | "go";
}

/** Every error `listGenerations` can produce, as a discriminated union. */
export type ProjectsListGenerationsError = UnauthorizedError | NotFoundError | UnexpectedApiError | TransportError | ValidationError;

/** Every error `generate` can produce, as a discriminated union. */
export type ProjectsGenerateError = UnauthorizedError | PaymentRequiredError | NotFoundError | UnprocessableEntityError | UnexpectedApiError | TransportError | ValidationError;

