// typeship — projects resource.
// Generated by typeship — https://typeship.dev

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import { paginate, PagePromise } from "../core/pagination.js";
import {
  ResponseParseError,
  TransportError,
  UnexpectedApiError,
  ValidationError,
  BadGatewayError,
  BadRequestError,
  ConflictError,
  ForbiddenError,
  InternalServerError,
  NotFoundError,
  PayloadTooLargeError,
  PaymentRequiredError,
  RateLimitedError,
  UnauthorizedError,
  UnprocessableEntityError,
} from "../errors.js";
import type {
  CreateProjectRequest,
  DeletedProject,
  DeletedProjectRead,
  DiagnosticRemediation,
  DiagnosticRemediationRead,
  DiagnosticRemediationRequest,
  DiagnosticReport,
  DiagnosticReportRead,
  GenerateProjectRequest,
  GenerationBatch,
  GenerationBatchRead,
  GenerationList,
  GenerationListRead,
  GenerationSummary,
  GenerationSummaryRead,
  Project,
  ProjectId,
  ProjectList,
  ProjectListRead,
  ProjectRead,
  ProjectSummary,
  ProjectSummaryRead,
  RepositoryIntegrationHealth,
  RepositoryIntegrationHealthRead,
  TargetId,
  UpdateProjectRequest,
} from "../types.js";

export class ProjectsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * List projects
   *
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /projects`
   */
  list(
    params?: ProjectsListParams,
    options?: RequestOptions,
  ): PagePromise<ProjectSummaryRead, ProjectsListError> {
    return paginate<ProjectSummaryRead, ProjectsListError>(this._core, {
      method: "GET",
      path: "/projects",
      security: [{"apiKey":[]}],
      query: {
        limit: params?.limit,
        cursor: params?.cursor,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "projects.list",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      hasMoreField: "has_more",
      limitParam: "limit",
    });
  }

  /**
   * Create a project
   *
   * Creates a Project from a URL or GitHub Definition.
   *
   * Free includes one saved Project, all selected Targets, and the first 25 operations per Target,
   * with regeneration, history, delivery pull requests, and previews. Pro supports additional
   * Projects and all operations. One-shot generation does not use a Project slot.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `POST /projects`
   */
  async create(
    body: CreateProjectRequest,
    params?: ProjectsCreateParams,
    options?: RequestOptions,
  ): Promise<ApiResult<ProjectRead, ProjectsCreateError>> {
    return this._core.request<ProjectRead, ProjectsCreateError>({
      method: "POST",
      path: "/projects",
      security: [{"apiKey":[]}],
      headers: {
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "402": PaymentRequiredError,
        "403": ForbiddenError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "projects.create",
      options,
    });
  }

  /**
   * Retrieve a project
   *
   * Returns the Project's settings and Definition ID. List its Targets separately to retrieve
   * Target configuration and Deliveries.
   * `GET /projects/{project_id}`
   */
  async retrieve(
    projectId: ProjectId,
    options?: RequestOptions,
  ): Promise<ApiResult<ProjectRead, ProjectsRetrieveError>> {
    return this._core.request<ProjectRead, ProjectsRetrieveError>({
      method: "GET",
      path: `/projects/${encodeURIComponent(String(projectId))}`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "projects.retrieve",
      options,
    });
  }

  /**
   * Delete a project
   *
   * A `502` response means the Project was not deleted because its release pull requests could not
   * be retired. Retry deletion to finish retiring the remaining reviews. Repeating a completed
   * deletion returns `404`.
   * `DELETE /projects/{project_id}`
   */
  async delete(
    projectId: ProjectId,
    options?: RequestOptions,
  ): Promise<ApiResult<DeletedProjectRead, ProjectsDeleteError>> {
    return this._core.request<DeletedProjectRead, ProjectsDeleteError>({
      method: "DELETE",
      path: `/projects/${encodeURIComponent(String(projectId))}`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
        "502": BadGatewayError,
      },
      idempotent: true,
      schemaKey: "projects.delete",
      options,
    });
  }

  /**
   * Update a project
   *
   * Omitted fields keep their current values. A supplied config replaces the entire stored object;
   * null or an empty object clears it.
   * Updates have no revision precondition. Concurrent updates preserve omitted fields, and the last
   * saved update to a supplied field wins.
   *
   * A `502` response means the Project was saved, but an obsolete release pull request could not be
   * retired. Retrieve the Project and retry the same update to finish retiring reviews if that
   * update is still desired.
   * `PATCH /projects/{project_id}`
   */
  async update(
    projectId: ProjectId,
    body: UpdateProjectRequest,
    options?: RequestOptions,
  ): Promise<ApiResult<ProjectRead, ProjectsUpdateError>> {
    return this._core.request<ProjectRead, ProjectsUpdateError>({
      method: "PATCH",
      path: `/projects/${encodeURIComponent(String(projectId))}`,
      security: [{"apiKey":[]}],
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "402": PaymentRequiredError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
        "502": BadGatewayError,
      },
      schemaKey: "projects.update",
      options,
    });
  }

  /**
   * Analyze a project's latest Definition Revision
   *
   * Checks the latest Definition Revision after applying its saved patches. Each finding groups
   * affected locations under a stable rule ID. A suggested patch is included only when the
   * Definition provides enough information to determine the correction.
   * `GET /projects/{project_id}/diagnostics`
   */
  async retrieveDiagnostics(
    projectId: ProjectId,
    options?: RequestOptions,
  ): Promise<ApiResult<DiagnosticReportRead, ProjectsRetrieveDiagnosticsError>> {
    return this._core.request<DiagnosticReportRead, ProjectsRetrieveDiagnosticsError>({
      method: "GET",
      path: `/projects/${encodeURIComponent(String(projectId))}/diagnostics`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "projects.retrieveDiagnostics",
      options,
    });
  }

  /**
   * Refresh a project's Diagnostics from its configured source
   *
   * Fetches the configured source and returns updated Diagnostics. Creates a Definition Revision
   * only when the content changes. Does not generate Targets or use a metered generation.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `POST /projects/{project_id}/diagnostics`
   */
  async refreshDiagnostics(
    projectId: ProjectId,
    params?: ProjectsRefreshDiagnosticsParams,
    options?: RequestOptions,
  ): Promise<ApiResult<DiagnosticReportRead, ProjectsRefreshDiagnosticsError>> {
    return this._core.request<DiagnosticReportRead, ProjectsRefreshDiagnosticsError>({
      method: "POST",
      path: `/projects/${encodeURIComponent(String(projectId))}/diagnostics`,
      security: [{"apiKey":[]}],
      headers: {
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "projects.refreshDiagnostics",
      options,
    });
  }

  /**
   * Apply exact, reviewed diagnostic remediations
   *
   * Applies reviewed patches from Diagnostics. For a repository source, opens or updates a source
   * pull request. For a URL source, saves Definition patches.
   *
   * Findings that need an API-owner decision return `422`. Read the finding's `authoring_brief` and
   * update the source instead.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `POST /projects/{project_id}/diagnostics/remediations`
   */
  async remediateDiagnostics(
    projectId: ProjectId,
    body: DiagnosticRemediationRequest,
    params?: ProjectsRemediateDiagnosticsParams,
    options?: RequestOptions,
  ): Promise<ApiResult<DiagnosticRemediationRead, ProjectsRemediateDiagnosticsError>> {
    return this._core.request<DiagnosticRemediationRead, ProjectsRemediateDiagnosticsError>({
      method: "POST",
      path: `/projects/${encodeURIComponent(String(projectId))}/diagnostics/remediations`,
      security: [{"apiKey":[]}],
      headers: {
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "projects.remediateDiagnostics",
      options,
    });
  }

  /**
   * Diagnose a project's repository integrations
   *
   * Checks repository access, Definition readability, source-approval labels, and required checks.
   * Includes the latest webhook delivery so you can investigate missing updates.
   * `GET /projects/{project_id}/integration-health`
   */
  async retrieveIntegrationHealth(
    projectId: ProjectId,
    options?: RequestOptions,
  ): Promise<ApiResult<RepositoryIntegrationHealthRead, ProjectsRetrieveIntegrationHealthError>> {
    return this._core.request<RepositoryIntegrationHealthRead, ProjectsRetrieveIntegrationHealthError>({
      method: "GET",
      path: `/projects/${encodeURIComponent(String(projectId))}/integration-health`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "projects.retrieveIntegrationHealth",
      options,
    });
  }

  /**
   * List a project's generations
   *
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /projects/{project_id}/generations`
   */
  listGenerations(
    projectId: ProjectId,
    params?: ProjectsListGenerationsParams,
    options?: RequestOptions,
  ): PagePromise<GenerationSummaryRead, ProjectsListGenerationsError> {
    return paginate<GenerationSummaryRead, ProjectsListGenerationsError>(this._core, {
      method: "GET",
      path: `/projects/${encodeURIComponent(String(projectId))}/generations`,
      security: [{"apiKey":[]}],
      query: {
        limit: params?.limit,
        cursor: params?.cursor,
        target_id: params?.targetId,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "projects.listGenerations",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      hasMoreField: "has_more",
      limitParam: "limit",
    });
  }

  /**
   * Start generation for active Targets
   *
   * Queues one Generation per active Target and returns their IDs. Retrieve each Generation until
   * its status moves from `queued` to `running` and then `succeeded` or `failed`. `succeeded` means
   * generated files are saved; check Delivery and Draft status separately for repository delivery
   * and pull requests. A Target already queued or running is returned without starting another
   * Generation. A matching Idempotency-Key replay returns the same Generations with their current
   * statuses.
   *
   * If the package already matches a destination and no Draft is open, delivery reports `pr_status:
   * no_changes` without creating a commit, branch, or pull request. An existing Draft stays open.
   * Automatic generation uses the same workflow.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `POST /projects/{project_id}/generations`
   */
  async generate(
    projectId: ProjectId,
    body?: GenerateProjectRequest,
    params?: ProjectsGenerateParams,
    options?: RequestOptions,
  ): Promise<ApiResult<GenerationBatchRead, ProjectsGenerateError>> {
    return this._core.request<GenerationBatchRead, ProjectsGenerateError>({
      method: "POST",
      path: `/projects/${encodeURIComponent(String(projectId))}/generations`,
      security: [{"apiKey":[]}],
      headers: {
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "402": PaymentRequiredError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "413": PayloadTooLargeError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
        "502": BadGatewayError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "projects.generate",
      options,
    });
  }
}

export interface ProjectsListParams {
  /**
   * Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits
   * representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400
   * invalid_request. List query parameters must appear only once; unrecognized parameters also
   * return 400.
   */
  limit?: number;
  /**
   * Opaque cursor from the preceding page's next_cursor. Valid only for the same account,
   * operation, filters, and ordering that issued it. Omit to start at the first page. Empty,
   * malformed, or repeated cursors return 400 invalid_request. The page limit may change between
   * requests.
   */
  cursor?: string;
}

/** Every error `list` can produce, as a discriminated union. */
export type ProjectsListError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface ProjectsCreateParams {
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated account and
   * operation; account-less generation uses a hashed network identity. Retrying the same method,
   * path, query, and JSON body replays the original response. Reusing the key with changed intent
   * returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Every error `create` can produce, as a discriminated union. */
export type ProjectsCreateError =
  | BadRequestError
  | UnauthorizedError
  | PaymentRequiredError
  | ForbiddenError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `retrieve` can produce, as a discriminated union. */
export type ProjectsRetrieveError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `delete` can produce, as a discriminated union. */
export type ProjectsDeleteError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | BadGatewayError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `update` can produce, as a discriminated union. */
export type ProjectsUpdateError =
  | BadRequestError
  | UnauthorizedError
  | PaymentRequiredError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | BadGatewayError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `retrieveDiagnostics` can produce, as a discriminated union. */
export type ProjectsRetrieveDiagnosticsError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface ProjectsRefreshDiagnosticsParams {
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated account and
   * operation; account-less generation uses a hashed network identity. Retrying the same method,
   * path, query, and JSON body replays the original response. Reusing the key with changed intent
   * returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Every error `refreshDiagnostics` can produce, as a discriminated union. */
export type ProjectsRefreshDiagnosticsError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface ProjectsRemediateDiagnosticsParams {
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated account and
   * operation; account-less generation uses a hashed network identity. Retrying the same method,
   * path, query, and JSON body replays the original response. Reusing the key with changed intent
   * returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Every error `remediateDiagnostics` can produce, as a discriminated union. */
export type ProjectsRemediateDiagnosticsError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `retrieveIntegrationHealth` can produce, as a discriminated union. */
export type ProjectsRetrieveIntegrationHealthError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface ProjectsListGenerationsParams {
  /**
   * Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits
   * representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400
   * invalid_request. List query parameters must appear only once; unrecognized parameters also
   * return 400.
   */
  limit?: number;
  /**
   * Opaque cursor from the preceding page's next_cursor. Valid only for the same account,
   * operation, filters, and ordering that issued it. Omit to start at the first page. Empty,
   * malformed, or repeated cursors return 400 invalid_request. The page limit may change between
   * requests.
   */
  cursor?: string;
  /** Only generations for this persisted Target. */
  targetId?: TargetId;
}

/** Every error `listGenerations` can produce, as a discriminated union. */
export type ProjectsListGenerationsError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface ProjectsGenerateParams {
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated account and
   * operation; account-less generation uses a hashed network identity. Retrying the same method,
   * path, query, and JSON body replays the original response. Reusing the key with changed intent
   * returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Every error `generate` can produce, as a discriminated union. */
export type ProjectsGenerateError =
  | BadRequestError
  | UnauthorizedError
  | PaymentRequiredError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | PayloadTooLargeError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | BadGatewayError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;
