// typeship — publications resource.
// Generated by typeship — https://typeship.dev

import { HttpCore, type RequestOptions } from "../core/http.js";
import { paginate, PagePromise } from "../core/pagination.js";
import {
  ResponseParseError,
  TransportError,
  UnexpectedApiError,
  ValidationError,
  BadRequestError,
  ForbiddenError,
  InternalServerError,
  NotFoundError,
  RateLimitedError,
  UnauthorizedError,
} from "../errors.js";
import type {
  Publication,
  PublicationId,
  PublicationList,
  PublicationListRead,
  PublicationRead,
  PublicationResponse,
  PublicationResponseRead,
  ReleaseId,
} from "../types.js";

export class PublicationsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * List publications
   *
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /publications`
   */
  list(
    params?: PublicationsListParams,
    options?: RequestOptions,
  ): PagePromise<PublicationRead, PublicationsListError> {
    return paginate<PublicationRead, PublicationsListError>(this._core, {
      method: "GET",
      path: "/publications",
      security: [{"apiKey":[]}],
      query: {
        limit: params?.limit,
        cursor: params?.cursor,
        release_id: params?.releaseId,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "publications.list",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      hasMoreField: "has_more",
      limitParam: "limit",
    });
  }

  /**
   * Get publishing status
   *
   * Returns the registry publishing status for a release. A status in another organization returns
   * 404 resource_not_found.
   * `GET /publications/{publication_id}`
   */
  async get(publicationId: PublicationId, options?: RequestOptions): Promise<PublicationResponseRead> {
    return this._core.requestData<PublicationResponseRead, PublicationsGetError>({
      method: "GET",
      path: `/publications/${encodeURIComponent(String(publicationId))}`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "publications.get",
      options,
    });
  }
}

export interface PublicationsListParams {
  /**
   * Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits
   * representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400
   * input_invalid. List query parameters must appear only once; repeated or unrecognized parameters
   * return 400 query_param_invalid.
   */
  limit?: number;
  /**
   * Opaque cursor from the preceding page's next_cursor. Valid only for the same organization,
   * operation, filters, and ordering that issued it. Omit to start at the first page. Empty or
   * malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start
   * again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may
   * change between requests.
   */
  cursor?: string;
  /** Only publications of this release. */
  releaseId?: ReleaseId;
}

/** Typed errors `list` can throw. */
export type PublicationsListError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Typed errors `get` can throw. */
export type PublicationsGetError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;
