// typeship — shares resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http";
import { TransportError, UnexpectedApiError, ApiResponseError, NotFoundError, PayloadTooLargeError } from "../errors";
import type { GenerationResult, Share } from "../types";

export class SharesResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * Create a public share from a generation result
   * 
   * Stores the generated output at a public URL. No authentication required.
   * `POST /shares`
   */
  async create(body: GenerationResult, options?: RequestOptions): Promise<ApiResult<Share, SharesCreateError>> {
    return this._core.request<Share, SharesCreateError>({
      method: "POST",
      path: "/shares",
      body,
      errors: { "413": PayloadTooLargeError, default: ApiResponseError },
      options,
    });
  }

  /**
   * Retrieve a share
   * `GET /shares/{share_id}`
   */
  async get(shareId: string, options?: RequestOptions): Promise<ApiResult<GenerationResult, SharesGetError>> {
    return this._core.request<GenerationResult, SharesGetError>({
      method: "GET",
      path: `/shares/${encodeURIComponent(String(shareId))}`,
      errors: { "404": NotFoundError },
      idempotent: true,
      options,
    });
  }
}

/** Every error `create` can produce, as a discriminated union. */
export type SharesCreateError = PayloadTooLargeError | ApiResponseError | UnexpectedApiError | TransportError;

/** Every error `get` can produce, as a discriminated union. */
export type SharesGetError = NotFoundError | UnexpectedApiError | TransportError;

