// typeship — specRevisions resource.
// Generated by typeship — https://typeship.dev

import { HttpCore, type RequestOptions } from "../core/http.js";
import { paginate, PagePromise } from "../core/pagination.js";
import {
  ResponseParseError,
  TransportError,
  UnexpectedApiError,
  ValidationError,
  BadRequestError,
  ForbiddenError,
  InternalServerError,
  NotFoundError,
  RateLimitedError,
  UnauthorizedError,
} from "../errors.js";
import type {
  SpecId,
  SpecRevision,
  SpecRevisionFile,
  SpecRevisionFileList,
  SpecRevisionFileListRead,
  SpecRevisionFileRead,
  SpecRevisionId,
  SpecRevisionList,
  SpecRevisionListRead,
  SpecRevisionRead,
  SpecRevisionResponse,
  SpecRevisionResponseRead,
} from "../types.js";

export class SpecRevisionsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * List Spec Revisions
   *
   * Lists Spec Revisions, newest first. Source content is not included; list a revision's files
   * with listSpecRevisionFiles.
   *
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /spec-revisions`
   */
  list(
    params?: SpecRevisionsListParams,
    options?: RequestOptions,
  ): PagePromise<SpecRevisionRead, SpecRevisionsListError> {
    return paginate<SpecRevisionRead, SpecRevisionsListError>(this._core, {
      method: "GET",
      path: "/spec-revisions",
      security: [{"apiKey":[]}],
      query: {
        limit: params?.limit,
        cursor: params?.cursor,
        spec_id: params?.specId,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "specRevisions.list",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      hasMoreField: "has_more",
      limitParam: "limit",
    });
  }

  /**
   * Get a Spec Revision
   *
   * Returns metadata for a saved Spec Revision with a Diagnostics summary. Pass
   * `include=diagnostics` to add every Diagnostic, evaluated with the Spec's current patches and
   * Diagnostic policy. List its source files and resolved document with listSpecRevisionFiles.
   * `GET /spec-revisions/{spec_revision_id}`
   */
  async get(
    specRevisionId: SpecRevisionId,
    params?: SpecRevisionsGetParams,
    options?: RequestOptions,
  ): Promise<SpecRevisionResponseRead> {
    return this._core.requestData<SpecRevisionResponseRead, SpecRevisionsGetError>({
      method: "GET",
      path: `/spec-revisions/${encodeURIComponent(String(specRevisionId))}`,
      security: [{"apiKey":[]}],
      query: {
        include: params?.include,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "specRevisions.get",
      options,
    });
  }

  /**
   * List a Spec Revision's files
   *
   * Lists the captured source files and the resolved document Typeship generated from, ordered by
   * path. Read content with getFile.
   *
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /spec-revisions/{spec_revision_id}/files`
   */
  listFiles(
    specRevisionId: SpecRevisionId,
    params?: SpecRevisionsListFilesParams,
    options?: RequestOptions,
  ): PagePromise<SpecRevisionFileRead, SpecRevisionsListFilesError> {
    return paginate<SpecRevisionFileRead, SpecRevisionsListFilesError>(this._core, {
      method: "GET",
      path: `/spec-revisions/${encodeURIComponent(String(specRevisionId))}/files`,
      security: [{"apiKey":[]}],
      query: {
        limit: params?.limit,
        cursor: params?.cursor,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "specRevisions.listFiles",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      hasMoreField: "has_more",
      limitParam: "limit",
    });
  }
}

export interface SpecRevisionsListParams {
  /**
   * Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits
   * representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400
   * invalid_request. List query parameters must appear only once; unrecognized parameters also
   * return 400.
   */
  limit?: number;
  /**
   * Opaque cursor from the preceding page's next_cursor. Valid only for the same organization,
   * operation, filters, and ordering that issued it. Omit to start at the first page. Empty,
   * malformed, or repeated cursors return 400 invalid_request. The page limit may change between
   * requests.
   */
  cursor?: string;
  /** Only revisions of this Spec. */
  specId?: SpecId;
}

/** Typed errors `list` can throw. */
export type SpecRevisionsListError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface SpecRevisionsGetParams {
  /**
   * Add related data to the response. `diagnostics` adds the `diagnostics` and `patch_diagnostics`
   * arrays.
   */
  include?: "diagnostics";
}

/** Typed errors `get` can throw. */
export type SpecRevisionsGetError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface SpecRevisionsListFilesParams {
  /**
   * Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits
   * representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400
   * invalid_request. List query parameters must appear only once; unrecognized parameters also
   * return 400.
   */
  limit?: number;
  /**
   * Opaque cursor from the preceding page's next_cursor. Valid only for the same organization,
   * operation, filters, and ordering that issued it. Omit to start at the first page. Empty,
   * malformed, or repeated cursors return 400 invalid_request. The page limit may change between
   * requests.
   */
  cursor?: string;
}

/** Typed errors `listFiles` can throw. */
export type SpecRevisionsListFilesError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;
