// typeship — specs resource.
// Generated by typeship — https://typeship.dev

import { HttpCore, type RequestOptions } from "../core/http.js";
import {
  ResponseParseError,
  TransportError,
  UnexpectedApiError,
  ValidationError,
  BadGatewayError,
  BadRequestError,
  ConflictError,
  ForbiddenError,
  InternalServerError,
  NotFoundError,
  PreconditionFailedError,
  RateLimitedError,
  UnauthorizedError,
  UnprocessableEntityError,
} from "../errors.js";
import type { Spec, SpecId, SpecRead, SpecUpdateRequest } from "../types.js";

export class SpecsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * Get a Spec
   * `GET /specs/{spec_id}`
   */
  async get(specId: SpecId, options?: RequestOptions): Promise<SpecRead> {
    return this._core.requestData<SpecRead, SpecsGetError>({
      method: "GET",
      path: `/specs/${encodeURIComponent(String(specId))}`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "specs.get",
      options,
    });
  }

  /**
   * Update and resolve a Spec
   *
   * Resolves the source files before saving the update and records a new Spec Revision when the
   * source changes.
   * Omitted fields remain unchanged; supplied objects and arrays replace the whole field.
   * If the Spec or its Project configuration changes during validation, returns 409
   * resource_changed without saving the rejected update. Retrieve the current Spec and Project,
   * reconcile your changes,
   * and submit a new request with a new Idempotency-Key if using one.
   *
   * See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for ETag
   * and If-Match.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `PATCH /specs/{spec_id}`
   */
  async update(
    specId: SpecId,
    body: SpecUpdateRequest,
    params?: SpecsUpdateParams,
    options?: RequestOptions,
  ): Promise<SpecRead> {
    return this._core.requestData<SpecRead, SpecsUpdateError>({
      method: "PATCH",
      path: `/specs/${encodeURIComponent(String(specId))}`,
      security: [{"apiKey":[]}],
      headers: {
        "If-Match": params?.ifMatch === undefined ? undefined : String(params?.ifMatch),
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "412": PreconditionFailedError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "specs.update",
      options,
    });
  }

  /**
   * Refresh a Spec from its configured source
   *
   * Fetches the configured source now and creates a new Spec Revision only when its content
   * changes. Diagnostics then reads that revision. If automatic generation is enabled, refresh
   * queues generation for active Targets even when the source is unchanged.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `POST /specs/{spec_id}/refresh`
   */
  async refresh(specId: SpecId, params?: SpecsRefreshParams, options?: RequestOptions): Promise<SpecRead> {
    return this._core.requestData<SpecRead, SpecsRefreshError>({
      method: "POST",
      path: `/specs/${encodeURIComponent(String(specId))}/refresh`,
      security: [{"apiKey":[]}],
      headers: {
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
        "502": BadGatewayError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "specs.refresh",
      options,
    });
  }
}

/** Typed errors `get` can throw. */
export type SpecsGetError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface SpecsUpdateParams {
  /**
   * ETag from a preceding response. The write applies only if the resource still has that version;
   * otherwise it returns 412 precondition_failed without changes. Omit to write the current
   * version. See https://typeship.dev/docs/typeship-api#conditional-writes.
   */
  ifMatch?: string;
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated organization
   * and operation; generation without an organization uses a hashed network identity. Retrying the
   * same method, path, query, If-Match header, and JSON body replays the original response. Reusing
   * the key with changed intent returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Typed errors `update` can throw. */
export type SpecsUpdateError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | PreconditionFailedError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface SpecsRefreshParams {
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated organization
   * and operation; generation without an organization uses a hashed network identity. Retrying the
   * same method, path, query, If-Match header, and JSON body replays the original response. Reusing
   * the key with changed intent returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Typed errors `refresh` can throw. */
export type SpecsRefreshError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | BadGatewayError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;
