// typeship — specVersions resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import { paginate, PagePromise } from "../core/pagination.js";
import { TransportError, UnexpectedApiError, ValidationError, BadRequestError, ForbiddenError, NotFoundError, RateLimitedError, UnauthorizedError } from "../errors.js";
import type { ProjectId, SpecVersion, SpecVersionId, SpecVersionList } from "../types.js";

export class SpecVersionsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * List the specs this project has generated from
   *
   * The audit trail behind a regeneration: which spec produced which SDK, and when it changed. Content is omitted from the list because specs run to megabytes.
   *
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /projects/{project_id}/spec_versions`
   */
  list(projectId: ProjectId, params?: SpecVersionsListParams, options?: RequestOptions): PagePromise<SpecVersion, SpecVersionsListError> {
    return paginate<SpecVersion, SpecVersionsListError>(this._core, {
      method: "GET",
      path: `/projects/${encodeURIComponent(String(projectId))}/spec_versions`,
      query: { limit: params?.limit, cursor: params?.cursor },
      errors: { "400": BadRequestError, "401": UnauthorizedError, "403": ForbiddenError, "404": NotFoundError, "429": RateLimitedError },
      idempotent: true,
      schemaKey: "specVersions.list",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      hasMoreField: "has_more",
      limitParam: "limit",
    });
  }

  /**
   * Retrieve a spec version
   *
   * One recorded spec, with its content. Storing every spec a project has generated from is only an audit trail if you can read one back and diff it against what shipped.
   * `GET /spec_versions/{spec_version_id}`
   */
  async retrieve(specVersionId: SpecVersionId, options?: RequestOptions): Promise<ApiResult<SpecVersion, SpecVersionsRetrieveError>> {
    return this._core.request<SpecVersion, SpecVersionsRetrieveError>({
      method: "GET",
      path: `/spec_versions/${encodeURIComponent(String(specVersionId))}`,
      errors: { "401": UnauthorizedError, "403": ForbiddenError, "404": NotFoundError, "429": RateLimitedError },
      idempotent: true,
      schemaKey: "specVersions.retrieve",
      options,
    });
  }

  /**
   * Retrieve a spec version's raw text
   *
   * The escape hatch for specs too large to inline, and the endpoint to pipe straight into a diff.
   * `GET /spec_versions/{spec_version_id}/content`
   */
  async retrieveContent(specVersionId: SpecVersionId, options?: RequestOptions): Promise<ApiResult<string, SpecVersionsRetrieveContentError>> {
    return this._core.request<string, SpecVersionsRetrieveContentError>({
      method: "GET",
      path: `/spec_versions/${encodeURIComponent(String(specVersionId))}/content`,
      errors: { "401": UnauthorizedError, "403": ForbiddenError, "404": NotFoundError, "429": RateLimitedError },
      idempotent: true,
      schemaKey: "specVersions.retrieveContent",
      options,
    });
  }
}

export interface SpecVersionsListParams {
  /** Maximum number of resources to return. */
  limit?: number;
  /** Opaque cursor from the preceding page's next_cursor. */
  cursor?: string;
}

/** Every error `list` can produce, as a discriminated union. */
export type SpecVersionsListError = BadRequestError | UnauthorizedError | ForbiddenError | NotFoundError | RateLimitedError | UnexpectedApiError | TransportError | ValidationError;

/** Every error `retrieve` can produce, as a discriminated union. */
export type SpecVersionsRetrieveError = UnauthorizedError | ForbiddenError | NotFoundError | RateLimitedError | UnexpectedApiError | TransportError | ValidationError;

/** Every error `retrieveContent` can produce, as a discriminated union. */
export type SpecVersionsRetrieveContentError = UnauthorizedError | ForbiddenError | NotFoundError | RateLimitedError | UnexpectedApiError | TransportError | ValidationError;

