// typeship — targets resource.
// Generated by typeship — https://typeship.dev

import { HttpCore, type RequestOptions } from "../core/http.js";
import { paginate, PagePromise } from "../core/pagination.js";
import {
  ResponseParseError,
  TransportError,
  UnexpectedApiError,
  ValidationError,
  BadGatewayError,
  BadRequestError,
  ConflictError,
  ForbiddenError,
  InternalServerError,
  NotFoundError,
  PaymentRequiredError,
  PreconditionFailedError,
  RateLimitedError,
  UnauthorizedError,
  UnprocessableEntityError,
} from "../errors.js";
import type {
  DeletedTarget,
  DeletedTargetRead,
  ProjectId,
  ReleaseResponse,
  ReleaseResponseRead,
  Target,
  TargetAdoption,
  TargetCreateRequest,
  TargetId,
  TargetList,
  TargetListRead,
  TargetRead,
  TargetResponse,
  TargetResponseRead,
  TargetUpdateRequest,
} from "../types.js";

export class TargetsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * List Targets
   *
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /targets`
   */
  list(params?: TargetsListParams, options?: RequestOptions): PagePromise<TargetRead, TargetsListError> {
    return paginate<TargetRead, TargetsListError>(this._core, {
      method: "GET",
      path: "/targets",
      security: [{"apiKey":[]}],
      query: {
        limit: params?.limit,
        cursor: params?.cursor,
        project_id: params?.projectId,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "targets.list",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      hasMoreField: "has_more",
      limitParam: "limit",
    });
  }

  /**
   * Create an independently configured Target
   *
   * Creates a Target with its own configuration, Deliveries, and release history. Multiple Targets
   * can use the same generator.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `POST /targets`
   */
  async create(
    body: TargetCreateRequest,
    params?: TargetsCreateParams,
    options?: RequestOptions,
  ): Promise<TargetResponseRead> {
    return this._core.requestData<TargetResponseRead, TargetsCreateError>({
      method: "POST",
      path: "/targets",
      security: [{"apiKey":[]}],
      headers: {
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "402": PaymentRequiredError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "targets.create",
      options,
    });
  }

  /**
   * Get a Target
   * `GET /targets/{target_id}`
   */
  async get(targetId: TargetId, options?: RequestOptions): Promise<TargetResponseRead> {
    return this._core.requestData<TargetResponseRead, TargetsGetError>({
      method: "GET",
      path: `/targets/${encodeURIComponent(String(targetId))}`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "targets.get",
      options,
    });
  }

  /**
   * Delete an unused Target
   *
   * Deletes a Target with no Generation history, release history, or active Draft. A `409
   * resource_has_dependencies` means one of those resources still depends on it. Retrieve the
   * Target, disable it instead, or resolve the dependency before retrying.
   *
   * See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for ETag
   * and If-Match.
   * `DELETE /targets/{target_id}`
   */
  async delete(
    targetId: TargetId,
    params?: TargetsDeleteParams,
    options?: RequestOptions,
  ): Promise<DeletedTargetRead> {
    return this._core.requestData<DeletedTargetRead, TargetsDeleteError>({
      method: "DELETE",
      path: `/targets/${encodeURIComponent(String(targetId))}`,
      security: [{"apiKey":[]}],
      headers: {
        "If-Match": params?.ifMatch === undefined ? undefined : String(params?.ifMatch),
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "412": PreconditionFailedError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "targets.delete",
      options,
    });
  }

  /**
   * Update a Target or its Deliveries
   *
   * Omitted fields keep their current values. Supplied config, checks, and deliveries replace their
   * complete stored values.
   * With Project auto_generate enabled, changing Target config, checks, or Deliveries queues that
   * Target's Generation. A queued or running Target reuses that Generation.
   * Omitting If-Match applies the update to the current resource; with If-Match, a stale ETag
   * returns 412 precondition_failed without saving.
   * Select the next version through PATCH /drafts/{draft_id} on the Target's draft_id.
   *
   * A `409 target_busy` means the Target is publishing; wait for it to finish. A `409
   * delivery_conflict` means another Target owns the requested repository tree; retrieve both
   * Targets, choose a free destination, and retry.
   * A `502` response means the update was saved, but retiring an obsolete review or regenerating
   * the Target failed. Retrieve the Target and follow the error's retryable and suggested_action
   * fields.
   * See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for ETag
   * and If-Match.
   * `PATCH /targets/{target_id}`
   */
  async update(
    targetId: TargetId,
    body: TargetUpdateRequest,
    params?: TargetsUpdateParams,
    options?: RequestOptions,
  ): Promise<TargetResponseRead> {
    return this._core.requestData<TargetResponseRead, TargetsUpdateError>({
      method: "PATCH",
      path: `/targets/${encodeURIComponent(String(targetId))}`,
      security: [{"apiKey":[]}],
      headers: {
        "If-Match": params?.ifMatch === undefined ? undefined : String(params?.ifMatch),
      },
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "402": PaymentRequiredError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "412": PreconditionFailedError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
        "502": BadGatewayError,
      },
      schemaKey: "targets.update",
      options,
    });
  }

  /**
   * Adopt a verified existing package as the latest release
   *
   * Checks the repository tag, package metadata, and registry artifact, then records the package as
   * an Imported latest release. Opens the first Typeship Draft at the next major version; review it
   * to establish the baseline for preserving existing code.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `POST /targets/{target_id}/adopt`
   */
  async adopt(
    targetId: TargetId,
    body: TargetAdoption,
    params?: TargetsAdoptParams,
    options?: RequestOptions,
  ): Promise<ReleaseResponseRead> {
    return this._core.requestData<ReleaseResponseRead, TargetsAdoptError>({
      method: "POST",
      path: `/targets/${encodeURIComponent(String(targetId))}/adopt`,
      security: [{"apiKey":[]}],
      headers: {
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "targets.adopt",
      options,
    });
  }
}

export interface TargetsListParams {
  /**
   * Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits
   * representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400
   * invalid_request. List query parameters must appear only once; unrecognized parameters also
   * return 400.
   */
  limit?: number;
  /**
   * Opaque cursor from the preceding page's next_cursor. Valid only for the same organization,
   * operation, filters, and ordering that issued it. Omit to start at the first page. Empty,
   * malformed, or repeated cursors return 400 invalid_request. The page limit may change between
   * requests.
   */
  cursor?: string;
  /** Only Targets in this Project. */
  projectId?: ProjectId;
}

/** Typed errors `list` can throw. */
export type TargetsListError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface TargetsCreateParams {
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated organization
   * and operation; generation without an organization uses a hashed network identity. Retrying the
   * same method, path, query, If-Match header, and JSON body replays the original response. Reusing
   * the key with changed intent returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Typed errors `create` can throw. */
export type TargetsCreateError =
  | BadRequestError
  | UnauthorizedError
  | PaymentRequiredError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Typed errors `get` can throw. */
export type TargetsGetError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface TargetsDeleteParams {
  /**
   * ETag from a preceding response. The write applies only if the resource still has that version;
   * otherwise it returns 412 precondition_failed without changes. Omit to write the current
   * version. See https://typeship.dev/docs/typeship-api#conditional-writes.
   */
  ifMatch?: string;
}

/** Typed errors `delete` can throw. */
export type TargetsDeleteError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | PreconditionFailedError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface TargetsUpdateParams {
  /**
   * ETag from a preceding response. The write applies only if the resource still has that version;
   * otherwise it returns 412 precondition_failed without changes. Omit to write the current
   * version. See https://typeship.dev/docs/typeship-api#conditional-writes.
   */
  ifMatch?: string;
}

/** Typed errors `update` can throw. */
export type TargetsUpdateError =
  | BadRequestError
  | UnauthorizedError
  | PaymentRequiredError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | PreconditionFailedError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | BadGatewayError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface TargetsAdoptParams {
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated organization
   * and operation; generation without an organization uses a hashed network identity. Retrying the
   * same method, path, query, If-Match header, and JSON body replays the original response. Reusing
   * the key with changed intent returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Typed errors `adopt` can throw. */
export type TargetsAdoptError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;
