// typeship — targets resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import { paginate, PagePromise } from "../core/pagination.js";
import {
  ResponseParseError,
  TransportError,
  UnexpectedApiError,
  ValidationError,
  BadGatewayError,
  BadRequestError,
  ConflictError,
  ForbiddenError,
  InternalServerError,
  NotFoundError,
  PaymentRequiredError,
  RateLimitedError,
  UnauthorizedError,
  UnprocessableEntityError,
} from "../errors.js";
import type {
  DeletedTarget,
  DeletedTargetRead,
  DiscardDraftCustomizations,
  DraftCodeUpdateResponse,
  DraftCodeUpdateResponseRead,
  DraftConflictsResponse,
  DraftConflictsResponseRead,
  DraftCustomizationsResponse,
  DraftCustomizationsResponseRead,
  DraftHistoryRecoveryResponse,
  DraftHistoryRecoveryResponseRead,
  ProjectId,
  RecoverDraftHistory,
  ResolveDraftConflicts,
  Target,
  TargetAdoption,
  TargetDraftResponse,
  TargetDraftResponseRead,
  TargetDraftUpdate,
  TargetFields,
  TargetId,
  TargetList,
  TargetListRead,
  TargetRead,
  TargetRelease,
  TargetReleaseId,
  TargetReleaseList,
  TargetReleaseListRead,
  TargetReleaseRead,
  TargetReleaseResponse,
  TargetReleaseResponseRead,
  TargetResponse,
  TargetResponseRead,
  TargetUpdateRequest,
} from "../types.js";

export class TargetsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * List a project's Targets
   *
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /projects/{project_id}/targets`
   */
  list(
    projectId: ProjectId,
    params?: TargetsListParams,
    options?: RequestOptions,
  ): PagePromise<TargetRead, TargetsListError> {
    return paginate<TargetRead, TargetsListError>(this._core, {
      method: "GET",
      path: `/projects/${encodeURIComponent(String(projectId))}/targets`,
      security: [{"apiKey":[]}],
      query: {
        limit: params?.limit,
        cursor: params?.cursor,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "targets.list",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      hasMoreField: "has_more",
      limitParam: "limit",
    });
  }

  /**
   * Create an independently configured Target
   *
   * Creates a Target with its own configuration, Deliveries, and release history. Multiple Targets
   * can use the same generator.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `POST /projects/{project_id}/targets`
   */
  async create(
    projectId: ProjectId,
    body: TargetFields,
    params?: TargetsCreateParams,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetResponseRead, TargetsCreateError>> {
    return this._core.request<TargetResponseRead, TargetsCreateError>({
      method: "POST",
      path: `/projects/${encodeURIComponent(String(projectId))}/targets`,
      security: [{"apiKey":[]}],
      headers: {
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "402": PaymentRequiredError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "targets.create",
      options,
    });
  }

  /**
   * Retrieve a Target
   * `GET /targets/{target_id}`
   */
  async retrieve(
    targetId: TargetId,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetResponseRead, TargetsRetrieveError>> {
    return this._core.request<TargetResponseRead, TargetsRetrieveError>({
      method: "GET",
      path: `/targets/${encodeURIComponent(String(targetId))}`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "targets.retrieve",
      options,
    });
  }

  /**
   * Delete an unused Target
   *
   * Deletes a Target with no Generation history, release history, or active Draft. Disable a Target
   * instead if it has any of these.
   * `DELETE /targets/{target_id}`
   */
  async delete(
    targetId: TargetId,
    options?: RequestOptions,
  ): Promise<ApiResult<DeletedTargetRead, TargetsDeleteError>> {
    return this._core.request<DeletedTargetRead, TargetsDeleteError>({
      method: "DELETE",
      path: `/targets/${encodeURIComponent(String(targetId))}`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "targets.delete",
      options,
    });
  }

  /**
   * Update a Target, its Deliveries, or its next reviewed version
   *
   * Omitted fields keep their current values. Supplied config, checks, and deliveries replace their
   * complete stored values.
   * Updates have no revision precondition. Concurrent updates preserve omitted fields, and the last
   * saved update to a supplied field wins.
   * Send proposed_version by itself; use the Draft endpoint for a version selection with an
   * optional revision precondition.
   *
   * A `502` response means the update was saved, but retiring an obsolete review or regenerating a
   * version selection failed. Retrieve the Target and follow the error's retryable and
   * suggested_action fields. Repeating an unfinished version selection resumes generation;
   * repeating a completed selection starts no new work.
   * `PATCH /targets/{target_id}`
   */
  async update(
    targetId: TargetId,
    body: TargetUpdateRequest,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetResponseRead, TargetsUpdateError>> {
    return this._core.request<TargetResponseRead, TargetsUpdateError>({
      method: "PATCH",
      path: `/targets/${encodeURIComponent(String(targetId))}`,
      security: [{"apiKey":[]}],
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "402": PaymentRequiredError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
        "502": BadGatewayError,
      },
      schemaKey: "targets.update",
      options,
    });
  }

  /**
   * List immutable releases for a Target
   *
   * Auto-paginates: `for await (const item of …)` walks every page.
   * `GET /targets/{target_id}/releases`
   */
  listReleases(
    targetId: TargetId,
    params?: TargetsListReleasesParams,
    options?: RequestOptions,
  ): PagePromise<TargetReleaseRead, TargetsListReleasesError> {
    return paginate<TargetReleaseRead, TargetsListReleasesError>(this._core, {
      method: "GET",
      path: `/targets/${encodeURIComponent(String(targetId))}/releases`,
      security: [{"apiKey":[]}],
      query: {
        limit: params?.limit,
        cursor: params?.cursor,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "targets.listReleases",
      options,
    }, {
      style: "cursor",
      itemsField: "data",
      cursorParam: "cursor",
      nextCursorField: "next_cursor",
      hasMoreField: "has_more",
      limitParam: "limit",
    });
  }

  /**
   * Retrieve a Target's rolling Draft release
   *
   * Returns Current's version, the proposed Draft version, readiness, and commit. Pass `revision`
   * as `expected_revision` when updating the Draft to avoid changing a newer candidate.
   * `GET /targets/{target_id}/draft`
   */
  async retrieveDraft(
    targetId: TargetId,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetDraftResponseRead, TargetsRetrieveDraftError>> {
    return this._core.request<TargetDraftResponseRead, TargetsRetrieveDraftError>({
      method: "GET",
      path: `/targets/${encodeURIComponent(String(targetId))}/draft`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "targets.retrieveDraft",
      options,
    });
  }

  /**
   * Select an exact Draft version or return to automatic versioning
   *
   * Checks your version choice against the required version bump, then regenerates the existing
   * Draft pull request.
   *
   * Send the last read revision as expected_revision to reject an intervening change with 409
   * stale_release_revision before saving or regenerating.
   * The precondition is optional; omitting it applies the selection to the current Draft. Version
   * is required; null restores automatic selection.
   *
   * A `502` response means the selected version was saved, but regeneration failed. Follow the
   * error's retryable and suggested_action fields. Repeating an unfinished selection resumes
   * generation; repeating a completed selection starts no new work. If using expected_revision,
   * retrieve the Draft and confirm the saved selection before retrying with its current revision.
   * `PATCH /targets/{target_id}/draft`
   */
  async updateDraft(
    targetId: TargetId,
    body: TargetDraftUpdate,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetDraftResponseRead, TargetsUpdateDraftError>> {
    return this._core.request<TargetDraftResponseRead, TargetsUpdateDraftError>({
      method: "PATCH",
      path: `/targets/${encodeURIComponent(String(targetId))}/draft`,
      security: [{"apiKey":[]}],
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
        "502": BadGatewayError,
      },
      schemaKey: "targets.updateDraft",
      options,
    });
  }

  /**
   * Adopt a verified existing package as Current
   *
   * Checks the repository tag, package metadata, and registry artifact, then records the package as
   * an Imported Current release. Opens the first Typeship Draft at the next major version; review
   * it to establish the baseline for preserving existing code.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `POST /targets/{target_id}/adopt`
   */
  async adoptRelease(
    targetId: TargetId,
    body: TargetAdoption,
    params?: TargetsAdoptReleaseParams,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetReleaseResponseRead, TargetsAdoptReleaseError>> {
    return this._core.request<TargetReleaseResponseRead, TargetsAdoptReleaseError>({
      method: "POST",
      path: `/targets/${encodeURIComponent(String(targetId))}/adopt`,
      security: [{"apiKey":[]}],
      headers: {
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "targets.adoptRelease",
      options,
    });
  }

  /**
   * Retrieve an immutable Target release
   * `GET /target_releases/{target_release_id}`
   */
  async retrieveRelease(
    targetReleaseId: TargetReleaseId,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetReleaseResponseRead, TargetsRetrieveReleaseError>> {
    return this._core.request<TargetReleaseResponseRead, TargetsRetrieveReleaseError>({
      method: "GET",
      path: `/target_releases/${encodeURIComponent(String(targetReleaseId))}`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "targets.retrieveRelease",
      options,
    });
  }

  /**
   * Retry publication of an exact Target release
   *
   * Retries publication of the specified release through its repository workflow. Uses that
   * release's version and accepted commit, even if a newer Draft or release exists.
   *
   * A `502` response means the repository publication workflow could not be dispatched.
   *
   * A `Idempotency-Key` UUID is generated per call (stable across retries) unless you pass one.
   * `POST /target_releases/{target_release_id}/republish`
   */
  async republishRelease(
    targetReleaseId: TargetReleaseId,
    params?: TargetsRepublishReleaseParams,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetReleaseResponseRead, TargetsRepublishReleaseError>> {
    return this._core.request<TargetReleaseResponseRead, TargetsRepublishReleaseError>({
      method: "POST",
      path: `/target_releases/${encodeURIComponent(String(targetReleaseId))}/republish`,
      security: [{"apiKey":[]}],
      headers: {
        "Idempotency-Key": params?.idempotencyKey === undefined ? undefined : String(params?.idempotencyKey),
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "429": RateLimitedError,
        "500": InternalServerError,
        "502": BadGatewayError,
      },
      idempotencyKey: "Idempotency-Key",
      schemaKey: "targets.republishRelease",
      options,
    });
  }

  /**
   * Inspect customizations on a Draft
   *
   * Returns the changed file paths from the latest Draft inspection. Read conflicts for all three
   * file versions, and read the Draft for package-check readiness.
   * `GET /targets/{target_id}/draft/customizations`
   */
  async retrieveDraftCustomizations(
    targetId: TargetId,
    options?: RequestOptions,
  ): Promise<ApiResult<DraftCustomizationsResponseRead, TargetsRetrieveDraftCustomizationsError>> {
    return this._core.request<DraftCustomizationsResponseRead, TargetsRetrieveDraftCustomizationsError>({
      method: "GET",
      path: `/targets/${encodeURIComponent(String(targetId))}/draft/customizations`,
      security: [{"apiKey":[]}],
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "targets.retrieveDraftCustomizations",
      options,
    });
  }

  /**
   * Inspect conflicts on a Draft
   *
   * Returns every conflict with its base, repository, and incoming file bytes and modes in one
   * response. An absent file is null. incoming_source distinguishes generated changes,
   * default-branch changes, and recovered saved Draft code. Saved decisions require a separate
   * Generate before conflicts clear.
   * `GET /targets/{target_id}/draft/conflicts`
   */
  async retrieveDraftConflicts(
    targetId: TargetId,
    params?: TargetsRetrieveDraftConflictsParams,
    options?: RequestOptions,
  ): Promise<ApiResult<DraftConflictsResponseRead, TargetsRetrieveDraftConflictsError>> {
    return this._core.request<DraftConflictsResponseRead, TargetsRetrieveDraftConflictsError>({
      method: "GET",
      path: `/targets/${encodeURIComponent(String(targetId))}/draft/conflicts`,
      security: [{"apiKey":[]}],
      query: {
        path: params?.path,
        after_path: params?.afterPath,
        content_offset: params?.contentOffset,
        expected_head_revision: params?.expectedHeadRevision,
      },
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      idempotent: true,
      schemaKey: "targets.retrieveDraftConflicts",
      options,
    });
  }

  /**
   * Resolve selected Draft conflicts
   *
   * Save deliberate decisions for the exact inspected Draft. Keep the repository or incoming side,
   * or submit final file content, including binary bytes. Decisions save atomically. Use dry_run to
   * preview them, then generate the Target separately to apply saved decisions and run its checks.
   * `POST /targets/{target_id}/draft/conflicts/resolve`
   */
  async resolveDraftConflicts(
    targetId: TargetId,
    body: ResolveDraftConflicts,
    options?: RequestOptions,
  ): Promise<ApiResult<DraftCodeUpdateResponseRead, TargetsResolveDraftConflictsError>> {
    return this._core.request<DraftCodeUpdateResponseRead, TargetsResolveDraftConflictsError>({
      method: "POST",
      path: `/targets/${encodeURIComponent(String(targetId))}/draft/conflicts/resolve`,
      security: [{"apiKey":[]}],
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      schemaKey: "targets.resolveDraftConflicts",
      options,
    });
  }

  /**
   * Discard selected Draft customizations
   *
   * Replace explicitly listed non-conflicting paths with generated files in one Draft commit.
   * Listing a customer-only file deletes it. Use dry_run to inspect writes and deletions first.
   * Resolve conflicts through the separate conflicts action. Generate afterward to refresh the
   * Draft and its checks.
   * `POST /targets/{target_id}/draft/customizations/discard`
   */
  async discardDraftCustomizations(
    targetId: TargetId,
    body: DiscardDraftCustomizations,
    options?: RequestOptions,
  ): Promise<ApiResult<DraftCodeUpdateResponseRead, TargetsDiscardDraftCustomizationsError>> {
    return this._core.request<DraftCodeUpdateResponseRead, TargetsDiscardDraftCustomizationsError>({
      method: "POST",
      path: `/targets/${encodeURIComponent(String(targetId))}/draft/customizations/discard`,
      security: [{"apiKey":[]}],
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      schemaKey: "targets.discardDraftCustomizations",
      options,
    });
  }

  /**
   * Review and recover rewritten repository history
   *
   * Preview a rewritten default branch and the Draft code to preserve. Approve the exact inspected
   * revisions with dry_run false, then Generate separately. Recovery preserves the previous Draft
   * branch, opens a new Draft from the current default branch, and requires explicit decisions for
   * overlapping code. A rewritten Draft alone recovers automatically during Generate.
   * `POST /targets/{target_id}/draft/history/recover`
   */
  async recoverDraftHistory(
    targetId: TargetId,
    body: RecoverDraftHistory,
    options?: RequestOptions,
  ): Promise<ApiResult<DraftHistoryRecoveryResponseRead, TargetsRecoverDraftHistoryError>> {
    return this._core.request<DraftHistoryRecoveryResponseRead, TargetsRecoverDraftHistoryError>({
      method: "POST",
      path: `/targets/${encodeURIComponent(String(targetId))}/draft/history/recover`,
      security: [{"apiKey":[]}],
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "429": RateLimitedError,
        "500": InternalServerError,
      },
      schemaKey: "targets.recoverDraftHistory",
      options,
    });
  }
}

export interface TargetsListParams {
  /**
   * Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits
   * representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400
   * invalid_request. List query parameters must appear only once; unrecognized parameters also
   * return 400.
   */
  limit?: number;
  /**
   * Opaque cursor from the preceding page's next_cursor. Valid only for the same account,
   * operation, filters, and ordering that issued it. Omit to start at the first page. Empty,
   * malformed, or repeated cursors return 400 invalid_request. The page limit may change between
   * requests.
   */
  cursor?: string;
}

/** Every error `list` can produce, as a discriminated union. */
export type TargetsListError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface TargetsCreateParams {
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated account and
   * operation; account-less generation uses a hashed network identity. Retrying the same method,
   * path, query, and JSON body replays the original response. Reusing the key with changed intent
   * returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Every error `create` can produce, as a discriminated union. */
export type TargetsCreateError =
  | BadRequestError
  | UnauthorizedError
  | PaymentRequiredError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `retrieve` can produce, as a discriminated union. */
export type TargetsRetrieveError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `delete` can produce, as a discriminated union. */
export type TargetsDeleteError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `update` can produce, as a discriminated union. */
export type TargetsUpdateError =
  | BadRequestError
  | UnauthorizedError
  | PaymentRequiredError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | BadGatewayError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface TargetsListReleasesParams {
  /**
   * Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits
   * representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400
   * invalid_request. List query parameters must appear only once; unrecognized parameters also
   * return 400.
   */
  limit?: number;
  /**
   * Opaque cursor from the preceding page's next_cursor. Valid only for the same account,
   * operation, filters, and ordering that issued it. Omit to start at the first page. Empty,
   * malformed, or repeated cursors return 400 invalid_request. The page limit may change between
   * requests.
   */
  cursor?: string;
}

/** Every error `listReleases` can produce, as a discriminated union. */
export type TargetsListReleasesError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `retrieveDraft` can produce, as a discriminated union. */
export type TargetsRetrieveDraftError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `updateDraft` can produce, as a discriminated union. */
export type TargetsUpdateDraftError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | BadGatewayError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface TargetsAdoptReleaseParams {
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated account and
   * operation; account-less generation uses a hashed network identity. Retrying the same method,
   * path, query, and JSON body replays the original response. Reusing the key with changed intent
   * returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Every error `adoptRelease` can produce, as a discriminated union. */
export type TargetsAdoptReleaseError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `retrieveRelease` can produce, as a discriminated union. */
export type TargetsRetrieveReleaseError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface TargetsRepublishReleaseParams {
  /**
   * Identifies one logical write for 24 hours. The key is scoped to the authenticated account and
   * operation; account-less generation uses a hashed network identity. Retrying the same method,
   * path, query, and JSON body replays the original response. Reusing the key with changed intent
   * returns 409. After expiry the key starts a new write.
   */
  idempotencyKey?: string;
}

/** Every error `republishRelease` can produce, as a discriminated union. */
export type TargetsRepublishReleaseError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | RateLimitedError
  | InternalServerError
  | BadGatewayError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `retrieveDraftCustomizations` can produce, as a discriminated union. */
export type TargetsRetrieveDraftCustomizationsError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

export interface TargetsRetrieveDraftConflictsParams {
  /** Inspect this conflict path only. */
  path?: string;
  /** Continue after next_path. Requires expected_head_revision. */
  afterPath?: string;
  /**
   * Decoded byte offset for each side. Select one path and follow each side until next_offset is
   * null.
   */
  contentOffset?: number;
  /** Exact Draft head from the preceding response. Required when continuing a page or byte offset. */
  expectedHeadRevision?: string;
}

/** Every error `retrieveDraftConflicts` can produce, as a discriminated union. */
export type TargetsRetrieveDraftConflictsError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `resolveDraftConflicts` can produce, as a discriminated union. */
export type TargetsResolveDraftConflictsError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `discardDraftCustomizations` can produce, as a discriminated union. */
export type TargetsDiscardDraftCustomizationsError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;

/** Every error `recoverDraftHistory` can produce, as a discriminated union. */
export type TargetsRecoverDraftHistoryError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | RateLimitedError
  | InternalServerError
  | UnexpectedApiError
  | ResponseParseError
  | TransportError
  | ValidationError;
