// typeship — targets resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, type ApiResult, type RequestOptions } from "../core/http.js";
import {
  TransportError,
  UnexpectedApiError,
  ValidationError,
  BadRequestError,
  ConflictError,
  ForbiddenError,
  NotFoundError,
  RateLimitedError,
  UnauthorizedError,
  UnprocessableEntityError,
} from "../errors.js";
import type {
  ProjectId,
  Target,
  TargetFields,
  TargetId,
  TargetList,
  TargetListRead,
  TargetRead,
  TargetRelease,
  TargetReleaseId,
  TargetReleaseList,
  TargetReleaseListRead,
  TargetReleaseRead,
  TargetUpdateRequest,
} from "../types.js";

export class TargetsResource {
  constructor(private readonly _core: HttpCore) {}
  /**
   * List a project's Targets
   * `GET /projects/{project_id}/targets`
   */
  async list(
    projectId: ProjectId,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetListRead, TargetsListError>> {
    return this._core.request<TargetListRead, TargetsListError>({
      method: "GET",
      path: `/projects/${encodeURIComponent(String(projectId))}/targets`,
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
      },
      idempotent: true,
      schemaKey: "targets.list",
      options,
    });
  }

  /**
   * Create an independently configured Target
   *
   * Several Targets may use the same generator with distinct configuration, Deliveries, and release
   * streams.
   * `POST /projects/{project_id}/targets`
   */
  async create(
    projectId: ProjectId,
    body: TargetFields,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetRead, TargetsCreateError>> {
    return this._core.request<TargetRead, TargetsCreateError>({
      method: "POST",
      path: `/projects/${encodeURIComponent(String(projectId))}/targets`,
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
      },
      schemaKey: "targets.create",
      options,
    });
  }

  /**
   * Retrieve a Target
   * `GET /targets/{target_id}`
   */
  async retrieve(
    targetId: TargetId,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetRead, TargetsRetrieveError>> {
    return this._core.request<TargetRead, TargetsRetrieveError>({
      method: "GET",
      path: `/targets/${encodeURIComponent(String(targetId))}`,
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
      },
      idempotent: true,
      schemaKey: "targets.retrieve",
      options,
    });
  }

  /**
   * Delete an unused Target
   *
   * Targets with Generation or release history, or an active release candidate, must be disabled
   * instead.
   * `DELETE /targets/{target_id}`
   */
  async delete(targetId: TargetId, options?: RequestOptions): Promise<ApiResult<void, TargetsDeleteError>> {
    return this._core.request<void, TargetsDeleteError>({
      method: "DELETE",
      path: `/targets/${encodeURIComponent(String(targetId))}`,
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "429": RateLimitedError,
      },
      idempotent: true,
      options,
    });
  }

  /**
   * Update a Target, its Deliveries, or its next reviewed version
   * `PATCH /targets/{target_id}`
   */
  async update(
    targetId: TargetId,
    body: TargetUpdateRequest,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetRead, TargetsUpdateError>> {
    return this._core.request<TargetRead, TargetsUpdateError>({
      method: "PATCH",
      path: `/targets/${encodeURIComponent(String(targetId))}`,
      body,
      errors: {
        "400": BadRequestError,
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "409": ConflictError,
        "422": UnprocessableEntityError,
        "429": RateLimitedError,
      },
      schemaKey: "targets.update",
      options,
    });
  }

  /**
   * List immutable releases for a Target
   * `GET /targets/{target_id}/releases`
   */
  async listReleases(
    targetId: TargetId,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetReleaseListRead, TargetsListReleasesError>> {
    return this._core.request<TargetReleaseListRead, TargetsListReleasesError>({
      method: "GET",
      path: `/targets/${encodeURIComponent(String(targetId))}/releases`,
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
      },
      idempotent: true,
      schemaKey: "targets.listReleases",
      options,
    });
  }

  /**
   * Retrieve an immutable Target release
   * `GET /target_releases/{target_release_id}`
   */
  async retrieveRelease(
    targetReleaseId: TargetReleaseId,
    options?: RequestOptions,
  ): Promise<ApiResult<TargetReleaseRead, TargetsRetrieveReleaseError>> {
    return this._core.request<TargetReleaseRead, TargetsRetrieveReleaseError>({
      method: "GET",
      path: `/target_releases/${encodeURIComponent(String(targetReleaseId))}`,
      errors: {
        "401": UnauthorizedError,
        "403": ForbiddenError,
        "404": NotFoundError,
        "429": RateLimitedError,
      },
      idempotent: true,
      schemaKey: "targets.retrieveRelease",
      options,
    });
  }
}

/** Every error `list` can produce, as a discriminated union. */
export type TargetsListError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | UnexpectedApiError
  | TransportError
  | ValidationError;

/** Every error `create` can produce, as a discriminated union. */
export type TargetsCreateError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | UnexpectedApiError
  | TransportError
  | ValidationError;

/** Every error `retrieve` can produce, as a discriminated union. */
export type TargetsRetrieveError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | UnexpectedApiError
  | TransportError
  | ValidationError;

/** Every error `delete` can produce, as a discriminated union. */
export type TargetsDeleteError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | RateLimitedError
  | UnexpectedApiError
  | TransportError
  | ValidationError;

/** Every error `update` can produce, as a discriminated union. */
export type TargetsUpdateError =
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | UnprocessableEntityError
  | RateLimitedError
  | UnexpectedApiError
  | TransportError
  | ValidationError;

/** Every error `listReleases` can produce, as a discriminated union. */
export type TargetsListReleasesError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | UnexpectedApiError
  | TransportError
  | ValidationError;

/** Every error `retrieveRelease` can produce, as a discriminated union. */
export type TargetsRetrieveReleaseError =
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | RateLimitedError
  | UnexpectedApiError
  | TransportError
  | ValidationError;
