// typeship — generated smoke tests for the drafts resource.
// Generated by typeship — https://typeship.dev
import test from "node:test";
import assert from "node:assert/strict";
import { TypeshipClient } from "../dist/index.js";
import { startMock } from "./helper.mjs";

test("drafts.list GET /drafts", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"data\":[{\"id\":\"drf_3q7m1v8k2p5d9h4c\",\"object\":\"draft\",\"target_id\":\"tgt_5m8q2v7k1p9d4h6c\",\"project_id\":\"prj_4f8k2m7x9q1v6b3n\",\"status\":\"idle\",\"reason\":\"conflict\",\"version_next\":\"example\",\"version_source\":\"automatic\",\"compatibility\":{\"api\":\"compatible\",\"package\":\"compatible\"},\"version\":{\"bump_required\":\"major\",\"correct\":true,\"previous\":\"example\"},\"errors\":[{\"type\":\"request\",\"code\":\"input_invalid\",\"phase\":\"spec\",\"target_id\":\"tgt_5m8q2v7k1p9d4h6c\",\"field\":\"example\",\"in\":\"body\",\"message\":\"example\",\"retryable\":true,\"suggested_action\":\"example\",\"docs_url\":\"https://example.com\"}],\"changes\":{\"changelog\":\"example\",\"breaking_count\":1},\"head_sha\":\"example\",\"pull_request\":{\"url\":\"https://example.com\",\"number\":1},\"generation_id\":\"gen_7h2p5d9c3m8w1k6q\",\"release_id\":\"rel_7m2q8v4k1p9d5h6c\",\"created_at\":\"2024-01-01T00:00:00Z\",\"updated_at\":\"2024-01-01T00:00:00Z\",\"conflicts\":{\"total\":1,\"decided\":1},\"customized_files\":1,\"history_recovery\":{\"default_sha\":\"example\",\"head_sha\":\"example\",\"preserved_branch\":\"example\"},\"request_id\":\"req_3k8m1v6q9p2d7h4c\",\"checks\":[{\"name\":\"example\",\"source\":\"typeship\",\"required\":true,\"status\":\"pending\",\"reason\":\"example\",\"commit_sha\":\"example\",\"url\":\"https://example.com\",\"observed_at\":\"2024-01-01T00:00:00Z\"}]}]}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.drafts.list(undefined);
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/drafts");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("drafts.get GET /drafts/{draft_id}", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"drf_3q7m1v8k2p5d9h4c\",\"object\":\"draft\",\"target_id\":\"tgt_5m8q2v7k1p9d4h6c\",\"project_id\":\"prj_4f8k2m7x9q1v6b3n\",\"status\":\"idle\",\"reason\":\"conflict\",\"version_next\":\"example\",\"version_source\":\"automatic\",\"compatibility\":{\"api\":\"compatible\",\"package\":\"compatible\"},\"version\":{\"bump_required\":\"major\",\"correct\":true,\"previous\":\"example\"},\"errors\":[{\"type\":\"request\",\"code\":\"input_invalid\",\"phase\":\"spec\",\"target_id\":\"tgt_5m8q2v7k1p9d4h6c\",\"field\":\"example\",\"in\":\"body\",\"message\":\"example\",\"retryable\":true,\"suggested_action\":\"example\",\"docs_url\":\"https://example.com\"}],\"changes\":{\"changelog\":\"example\",\"breaking_count\":1},\"head_sha\":\"example\",\"pull_request\":{\"url\":\"https://example.com\",\"number\":1},\"generation_id\":\"gen_7h2p5d9c3m8w1k6q\",\"release_id\":\"rel_7m2q8v4k1p9d5h6c\",\"created_at\":\"2024-01-01T00:00:00Z\",\"updated_at\":\"2024-01-01T00:00:00Z\",\"conflicts\":{\"total\":1,\"decided\":1},\"customized_files\":1,\"history_recovery\":{\"default_sha\":\"example\",\"head_sha\":\"example\",\"preserved_branch\":\"example\"},\"request_id\":\"req_3k8m1v6q9p2d7h4c\",\"checks\":[{\"name\":\"example\",\"source\":\"typeship\",\"required\":true,\"status\":\"pending\",\"reason\":\"example\",\"commit_sha\":\"example\",\"url\":\"https://example.com\",\"observed_at\":\"2024-01-01T00:00:00Z\"}]}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.drafts.get("test-draft_id");
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/drafts/test-draft_id");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("drafts.update PATCH /drafts/{draft_id}", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"drf_3q7m1v8k2p5d9h4c\",\"object\":\"draft\",\"target_id\":\"tgt_5m8q2v7k1p9d4h6c\",\"project_id\":\"prj_4f8k2m7x9q1v6b3n\",\"status\":\"idle\",\"reason\":\"conflict\",\"version_next\":\"example\",\"version_source\":\"automatic\",\"compatibility\":{\"api\":\"compatible\",\"package\":\"compatible\"},\"version\":{\"bump_required\":\"major\",\"correct\":true,\"previous\":\"example\"},\"errors\":[{\"type\":\"request\",\"code\":\"input_invalid\",\"phase\":\"spec\",\"target_id\":\"tgt_5m8q2v7k1p9d4h6c\",\"field\":\"example\",\"in\":\"body\",\"message\":\"example\",\"retryable\":true,\"suggested_action\":\"example\",\"docs_url\":\"https://example.com\"}],\"changes\":{\"changelog\":\"example\",\"breaking_count\":1},\"head_sha\":\"example\",\"pull_request\":{\"url\":\"https://example.com\",\"number\":1},\"generation_id\":\"gen_7h2p5d9c3m8w1k6q\",\"release_id\":\"rel_7m2q8v4k1p9d5h6c\",\"created_at\":\"2024-01-01T00:00:00Z\",\"updated_at\":\"2024-01-01T00:00:00Z\",\"conflicts\":{\"total\":1,\"decided\":1},\"customized_files\":1,\"history_recovery\":{\"default_sha\":\"example\",\"head_sha\":\"example\",\"preserved_branch\":\"example\"},\"request_id\":\"req_3k8m1v6q9p2d7h4c\",\"checks\":[{\"name\":\"example\",\"source\":\"typeship\",\"required\":true,\"status\":\"pending\",\"reason\":\"example\",\"commit_sha\":\"example\",\"url\":\"https://example.com\",\"observed_at\":\"2024-01-01T00:00:00Z\"}]}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.drafts.update("test-draft_id", {"version_next":"example"}, undefined);
    const request = mock.requests[0];
    assert.equal(request.method, "PATCH");
    assert.equal(request.path.split("?")[0], "/drafts/test-draft_id");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("drafts.listFiles GET /drafts/{draft_id}/files", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"data\":[{\"object\":\"draft_file\",\"path\":\"example\",\"customization\":\"added\",\"conflict\":{\"type\":\"no_common_version\",\"source\":\"generation\",\"decision\":\"yours\"},\"history\":{\"change\":\"added\",\"draft_differs\":true},\"sides\":{\"base\":\"file_4k8m2v7q1p9d5h6c\",\"yours\":\"file_4k8m2v7q1p9d5h6c\",\"generated\":\"file_4k8m2v7q1p9d5h6c\"}}]}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.drafts.listFiles("test-draft_id", undefined);
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/drafts/test-draft_id/files");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("drafts.resolve POST /drafts/{draft_id}/resolve", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"drf_3q7m1v8k2p5d9h4c\",\"object\":\"draft\",\"target_id\":\"tgt_5m8q2v7k1p9d4h6c\",\"project_id\":\"prj_4f8k2m7x9q1v6b3n\",\"status\":\"idle\",\"reason\":\"conflict\",\"version_next\":\"example\",\"version_source\":\"automatic\",\"compatibility\":{\"api\":\"compatible\",\"package\":\"compatible\"},\"version\":{\"bump_required\":\"major\",\"correct\":true,\"previous\":\"example\"},\"errors\":[{\"type\":\"request\",\"code\":\"input_invalid\",\"phase\":\"spec\",\"target_id\":\"tgt_5m8q2v7k1p9d4h6c\",\"field\":\"example\",\"in\":\"body\",\"message\":\"example\",\"retryable\":true,\"suggested_action\":\"example\",\"docs_url\":\"https://example.com\"}],\"changes\":{\"changelog\":\"example\",\"breaking_count\":1},\"head_sha\":\"example\",\"pull_request\":{\"url\":\"https://example.com\",\"number\":1},\"generation_id\":\"gen_7h2p5d9c3m8w1k6q\",\"release_id\":\"rel_7m2q8v4k1p9d5h6c\",\"created_at\":\"2024-01-01T00:00:00Z\",\"updated_at\":\"2024-01-01T00:00:00Z\",\"conflicts\":{\"total\":1,\"decided\":1},\"customized_files\":1,\"history_recovery\":{\"default_sha\":\"example\",\"head_sha\":\"example\",\"preserved_branch\":\"example\"},\"request_id\":\"req_3k8m1v6q9p2d7h4c\",\"checks\":[{\"name\":\"example\",\"source\":\"typeship\",\"required\":true,\"status\":\"pending\",\"reason\":\"example\",\"commit_sha\":\"example\",\"url\":\"https://example.com\",\"observed_at\":\"2024-01-01T00:00:00Z\"}]}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.drafts.resolve("test-draft_id", {"expected_head_sha":"0123456789abcdef0123456789abcdef01234567","resolutions":[{"path":"example","keep":"yours"}]});
    const request = mock.requests[0];
    assert.equal(request.method, "POST");
    assert.equal(request.path.split("?")[0], "/drafts/test-draft_id/resolve");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("drafts.recover POST /drafts/{draft_id}/recover", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"drf_3q7m1v8k2p5d9h4c\",\"object\":\"draft\",\"target_id\":\"tgt_5m8q2v7k1p9d4h6c\",\"project_id\":\"prj_4f8k2m7x9q1v6b3n\",\"status\":\"idle\",\"reason\":\"conflict\",\"version_next\":\"example\",\"version_source\":\"automatic\",\"compatibility\":{\"api\":\"compatible\",\"package\":\"compatible\"},\"version\":{\"bump_required\":\"major\",\"correct\":true,\"previous\":\"example\"},\"errors\":[{\"type\":\"request\",\"code\":\"input_invalid\",\"phase\":\"spec\",\"target_id\":\"tgt_5m8q2v7k1p9d4h6c\",\"field\":\"example\",\"in\":\"body\",\"message\":\"example\",\"retryable\":true,\"suggested_action\":\"example\",\"docs_url\":\"https://example.com\"}],\"changes\":{\"changelog\":\"example\",\"breaking_count\":1},\"head_sha\":\"example\",\"pull_request\":{\"url\":\"https://example.com\",\"number\":1},\"generation_id\":\"gen_7h2p5d9c3m8w1k6q\",\"release_id\":\"rel_7m2q8v4k1p9d5h6c\",\"created_at\":\"2024-01-01T00:00:00Z\",\"updated_at\":\"2024-01-01T00:00:00Z\",\"conflicts\":{\"total\":1,\"decided\":1},\"customized_files\":1,\"history_recovery\":{\"default_sha\":\"example\",\"head_sha\":\"example\",\"preserved_branch\":\"example\"},\"request_id\":\"req_3k8m1v6q9p2d7h4c\",\"checks\":[{\"name\":\"example\",\"source\":\"typeship\",\"required\":true,\"status\":\"pending\",\"reason\":\"example\",\"commit_sha\":\"example\",\"url\":\"https://example.com\",\"observed_at\":\"2024-01-01T00:00:00Z\"}]}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.drafts.recover("test-draft_id", {"expected_default_sha":"example","expected_head_sha":"example"});
    const request = mock.requests[0];
    assert.equal(request.method, "POST");
    assert.equal(request.path.split("?")[0], "/drafts/test-draft_id/recover");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});
