// Typeship — generated smoke tests for the files resource.
// Generated by Typeship — https://typeship.dev
import test from "node:test";
import assert from "node:assert/strict";
import { TypeshipClient } from "../dist/index.js";
import { startMock } from "./helper.mjs";

test("files.get GET /files/{file_id}", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"file_4k8m2v7q1p9d5h6c\",\"object\":\"file\",\"path\":\"path/to/file.txt\",\"size_bytes\":1,\"sha256\":\"abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789\",\"encoding\":\"utf8\",\"mode\":\"100644\",\"created_at\":\"2026-01-15T12:00:00Z\",\"content\":\"Hello, world!\",\"offset\":1,\"next_cursor\":\"example\",\"request_id\":\"req_3k8m1v6q9p2d7h4c\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.files.get("test-file_id", undefined);
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/files/test-file_id");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});
