// typeship — generated smoke tests for the generate resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.
import test from "node:test";
import assert from "node:assert/strict";
import { TypeshipClient } from "../dist/index.js";
import { startMock } from "./helper.mjs";

test("generate.run POST /generate", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"files\":[{\"path\":\"example\",\"content\":\"example\",\"mode\":\"100644\"}],\"warnings\":[\"example\"],\"meta\":{\"title\":\"example\",\"api_version\":\"example\",\"version\":\"example\",\"spec_format\":\"openapi\",\"oas_version\":\"example\",\"converted\":true,\"artifact_name\":\"example\",\"client_name\":\"example\",\"generators\":[\"typescript-sdk\"],\"resource_count\":1,\"operation_count\":1,\"schema_count\":1,\"paginated_operation_count\":1,\"omitted_operation_count\":1,\"omitted_operations\":[\"example\"],\"pr_url\":\"example\",\"pr_number\":1,\"pr_status\":\"opened\",\"pr_error\":\"example\",\"changelog\":\"example\",\"breaking_count\":1,\"baseline\":\"destination\",\"api_compatibility\":\"compatible\",\"package_compatibility\":\"compatible\",\"version_correct\":true,\"release_readiness\":\"success\",\"release_readiness_note\":\"example\",\"previous_version\":\"example\",\"integration_attempt_id\":\"int_8m2q5v1k9p4d7h3c\",\"customer_change_count\":1,\"integration_state\":\"conflicted\",\"reused_resolution_count\":1,\"published_compatibility\":\"compatible\",\"published_version\":\"example\",\"file_count\":1,\"total_lines\":1,\"diagnostics\":{\"format\":\"openapi\",\"summary\":{\"diagnostics\":1,\"occurrences\":1,\"errors\":1,\"warnings\":1,\"suggestions\":1,\"auto_fixable\":1}}},\"limits\":{\"max_operations\":1,\"generated_operations\":1,\"omitted_operations\":1,\"total_operations\":1,\"reason\":\"anonymous\",\"signup_url\":\"example\",\"upgrade_url\":\"example\"},\"claim\":null,\"request_id\":\"req_3k8m1v6q9p2d7h4c\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, bearerToken: "test-token" });
    const result = await client.generate.run({"definition":{"url":"https://example.com","headers":{}},"target":{"generator":"typescript-sdk"},"package_name":"example","module_path":"example","config":{"globals":["example"],"retries":{"max_retries":1,"statuses":[1],"initial_delay_ms":1,"max_delay_ms":1,"retry_non_idempotent":true,"disabled":true,"operations":{}},"pagination":{},"graphql":{"endpoint":"https://example.com","environments":[{"name":"example","url":"https://example.com"}],"auth":"bearer","api_key_header":"example","title":"example","scalars":{}},"auth":{"oauth_server":{"issuer":"https://example.com","discovery_url":"https://example.com","authorization_url":"https://example.com","token_url":"https://example.com","device_authorization_url":"https://example.com","scopes":["S123"],"audience":"example","resource":"https://example.com"},"oauth_applications":{},"oauth_application":"example","identity_verification":{"operation":"resource.method","subject_field":"example","account_field":"example","organization_field":"example"},"approval_url":"https://example.com","environments":{}},"cli":{"command_name":"example","update_notice":true,"support_url":"example","mcp_url":"example","skills_repo":"example"},"mcp":{"registry_name":"example","access":{"issuer":"https://example.com","resource":"https://example.com","jwks_url":"https://example.com","scopes":["example"]},"tool_mode":"auto","instructions":"example","tool_descriptions":{},"reference_resolvers":{}},"readme":{"quickstart_operation":"example"},"package":{"homepage":"example","license":"example","license_text":"example","copyright":"example","go_package_name":"example"},"docs_url":"example","docs_index_url":"https://example.com"}}, undefined);
    assert.equal(result.ok, true, JSON.stringify(result));
    const request = mock.requests[0];
    assert.equal(request.method, "POST");
    assert.equal(request.path.split("?")[0], "/generate");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});
