// typeship — generated smoke tests for the generate resource.
// Generated by typeship — https://typeship.dev
import test from "node:test";
import assert from "node:assert/strict";
import { TypeshipClient } from "../dist/index.js";
import { startMock } from "./helper.mjs";

test("generate.run POST /generate", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"files\":[{\"path\":\"example\",\"content\":\"example\",\"mode\":\"100644\"}],\"download\":{\"url\":\"https://example.com\",\"expires_at\":\"2024-01-01T00:00:00Z\",\"sha256\":\"example\",\"size_bytes\":1,\"file_count\":1},\"warnings\":[{\"code\":\"example\",\"message\":\"example\",\"operation\":\"example\"}],\"coverage\":{\"generated\":1,\"omitted\":1,\"total\":1,\"omitted_operations\":[\"example\"],\"reason\":\"anonymous\",\"signup_url\":\"https://example.com\",\"upgrade_url\":\"https://example.com\"},\"claim\":null,\"request_id\":\"req_3k8m1v6q9p2d7h4c\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.generate.run({"spec":{"url":"https://example.com","headers":{}},"target":{"type":"cli"},"package_name":"example","module_path":"example","go_sdk":{"module_path":"example","version":"example","spec_digest":"example","package_name":"example"},"config":{"globals":["example"],"retries":{"max_retries":1,"statuses":[1],"initial_delay_ms":1,"max_delay_ms":1,"retry_non_idempotent":true,"disabled":true,"operations":{}},"pagination":{},"graphql":{"endpoint":"https://example.com","environments":[{"name":"example","url":"https://example.com"}],"auth":"bearer","api_key_header":"example","title":"example","scalars":{}},"auth":{"oauth_server":{"issuer":"https://example.com","discovery_url":"https://example.com","authorization_url":"https://example.com","token_url":"https://example.com","device_authorization_url":"https://example.com","scopes":["S123"],"audience":"example","resource":"https://example.com"},"oauth_applications":{},"oauth_application":"example","identity_verification":{"subject_field":"/id","account_field":"/account_id","organization_field":"/organization_id"},"approval_url":"https://example.com","environments":{}},"cli":{"command_name":"example","update_notice":true,"changelog_url":"example","support_url":"example","mcp_url":"example","skills_repo":"example"},"mcp":{"registry_name":"example","access":{"issuer":"https://example.com","resource":"https://example.com","jwks_url":"https://example.com","scopes":["example"]},"tool_mode":"auto","instructions":"example","tool_descriptions":{},"reference_resolvers":{}},"readme":{"quickstart_operation":"example"},"package":{"homepage":"example","license":"example","license_text":"example","copyright":"example","go_package_name":"example"},"docs_url":"https://example.com","docs_index_url":"https://example.com"}}, undefined);
    const request = mock.requests[0];
    assert.equal(request.method, "POST");
    assert.equal(request.path.split("?")[0], "/generate");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("generate.downloadPackage GET /generate/download", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "\"example\"" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {} });
    const result = await client.generate.downloadPackage({"token":"example"});
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/generate/download");

  } finally {
    mock.close();
  }
});
