// typeship — generated smoke tests for the generations resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.
import test from "node:test";
import assert from "node:assert/strict";
import { TypeshipClient } from "../dist/index.js";
import { startMock } from "./helper.mjs";

test("generations.retrieve GET /generations/{generation_id}", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"gen_7h2p5d9c3m8w1k6q\",\"object\":\"generation\",\"project_id\":\"prj_4f8k2m7x9q1v6b3n\",\"status\":\"succeeded\",\"trigger\":\"manual\",\"output\":\"typescript-sdk\",\"meta\":{\"title\":\"Acme Payments API\",\"version\":\"1.0.0\",\"oas_version\":\"3.1\",\"package_name\":\"@acme/payments\",\"client_name\":\"AcmeClient\",\"outputs\":[\"typescript-sdk\"]},\"warnings\":[],\"error\":null,\"created_at\":\"2026-01-01T00:00:00Z\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, bearerToken: "test-token" });
    const result = await client.generations.retrieve("test-generation_id");
    assert.equal(result.ok, true, JSON.stringify(result));
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/generations/test-generation_id");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("generations.retrieveFile GET /generations/{generation_id}/file", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "\"example\"" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, bearerToken: "test-token" });
    const result = await client.generations.retrieveFile("test-generation_id", {"path":"example"});
    assert.equal(result.ok, true, JSON.stringify(result));
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/generations/test-generation_id/file");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});
