// Shared mock for the generated tests. Zero dependencies: node:http only.
// Generated by typeship — https://typeship.dev — do not edit by hand.
import { createServer } from "node:http";

export function startMock(response) {
  const requests = [];
  const server = createServer((req, res) => {
    let body = "";
    req.on("data", (chunk) => (body += chunk));
    req.on("end", () => {
      requests.push({ method: req.method, path: req.url, headers: req.headers, body });
      res.statusCode = response.status;
      res.setHeader("content-type", response.contentType);
      res.end(response.body);
    });
  });
  return new Promise((resolve) => {
    server.listen(0, "127.0.0.1", () => {
      const { port } = server.address();
      resolve({ url: "http://127.0.0.1:" + port, requests, close: () => server.close() });
    });
  });
}
