// typeship — generated smoke tests for the organization resource.
// Generated by typeship — https://typeship.dev
import test from "node:test";
import assert from "node:assert/strict";
import { TypeshipClient } from "../dist/index.js";
import { startMock } from "./helper.mjs";

test("organization.get GET /organization", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"example\",\"object\":\"organization\",\"name\":\"example\",\"plan\":\"free\",\"created_at\":\"2024-01-01T00:00:00Z\",\"updated_at\":\"2024-01-01T00:00:00Z\",\"request_id\":\"req_3k8m1v6q9p2d7h4c\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.organization.get();
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/organization");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});
