// typeship — generated smoke tests for the projects resource.
// Generated by typeship — https://typeship.dev — do not edit by hand.
import test from "node:test";
import assert from "node:assert/strict";
import { TypeshipClient } from "../dist/index.js";
import { startMock } from "./helper.mjs";

test("projects.list GET /projects", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"data\":[{\"id\":\"example\",\"object\":\"project\",\"name\":\"example\",\"spec_url\":\"example\",\"source\":{\"kind\":\"url\",\"url\":\"example\",\"repo\":\"example\",\"path\":\"example\"},\"destination\":{\"repo\":\"example\",\"directory\":\"example\"},\"languages\":[\"typescript\"],\"destinations\":{},\"package_names\":{},\"auto_regen\":true,\"package_name\":\"example\",\"spec_patches\":[{\"op\":\"set\",\"path\":\"example\",\"value\":{},\"to\":\"example\",\"reason\":\"example\"}],\"config\":{\"globals\":[{}],\"retries\":{\"max_retries\":{},\"statuses\":{},\"initial_delay_ms\":{},\"max_delay_ms\":{},\"retry_non_idempotent\":{},\"disabled\":{},\"operations\":{}},\"pagination\":{},\"cli\":{\"whoami_operation\":{},\"oauth_client_id\":{},\"oauth_scopes\":{},\"oauth_audience\":{},\"update_notice\":{},\"support_url\":{}},\"mcp\":{\"tool_mode\":{}},\"docs_url\":\"example\"},\"mcp_enabled\":true,\"mcp_url\":\"example\",\"agent_context_enabled\":true,\"agent_context_url\":\"example\",\"relay_enabled\":true,\"platforms\":[\"sdk\"],\"created_at\":\"2024-01-01T00:00:00Z\"}]}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, bearerToken: "test-token" });
    const result = await client.projects.list(undefined);
    assert.equal(result.ok, true, JSON.stringify(result));
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/projects");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("projects.create POST /projects", async () => {
  const mock = await startMock({ status: 201, contentType: "application/json", body: "{\"id\":\"example\",\"object\":\"project\",\"name\":\"example\",\"spec_url\":\"example\",\"source\":{\"kind\":\"url\",\"url\":\"example\",\"repo\":\"example\",\"path\":\"example\"},\"destination\":{\"repo\":\"example\",\"directory\":\"example\"},\"languages\":[\"typescript\"],\"destinations\":{},\"package_names\":{},\"auto_regen\":true,\"package_name\":\"example\",\"spec_patches\":[{\"op\":\"set\",\"path\":\"example\",\"value\":{},\"to\":\"example\",\"reason\":\"example\"}],\"config\":{\"globals\":[{}],\"retries\":{\"max_retries\":{},\"statuses\":{},\"initial_delay_ms\":{},\"max_delay_ms\":{},\"retry_non_idempotent\":{},\"disabled\":{},\"operations\":{}},\"pagination\":{},\"cli\":{\"whoami_operation\":{},\"oauth_client_id\":{},\"oauth_scopes\":{},\"oauth_audience\":{},\"update_notice\":{},\"support_url\":{}},\"mcp\":{\"tool_mode\":{}},\"docs_url\":\"example\"},\"mcp_enabled\":true,\"mcp_url\":\"example\",\"agent_context_enabled\":true,\"agent_context_url\":\"example\",\"relay_enabled\":true,\"platforms\":[\"sdk\"],\"created_at\":\"2024-01-01T00:00:00Z\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, bearerToken: "test-token" });
    const result = await client.projects.create({"name":"example"});
    assert.equal(result.ok, true, JSON.stringify(result));
    const request = mock.requests[0];
    assert.equal(request.method, "POST");
    assert.equal(request.path.split("?")[0], "/projects");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("projects.get GET /projects/{project_id}", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"example\",\"object\":\"project\",\"name\":\"example\",\"spec_url\":\"example\",\"source\":{\"kind\":\"url\",\"url\":\"example\",\"repo\":\"example\",\"path\":\"example\"},\"destination\":{\"repo\":\"example\",\"directory\":\"example\"},\"languages\":[\"typescript\"],\"destinations\":{},\"package_names\":{},\"auto_regen\":true,\"package_name\":\"example\",\"spec_patches\":[{\"op\":\"set\",\"path\":\"example\",\"value\":{},\"to\":\"example\",\"reason\":\"example\"}],\"config\":{\"globals\":[{}],\"retries\":{\"max_retries\":{},\"statuses\":{},\"initial_delay_ms\":{},\"max_delay_ms\":{},\"retry_non_idempotent\":{},\"disabled\":{},\"operations\":{}},\"pagination\":{},\"cli\":{\"whoami_operation\":{},\"oauth_client_id\":{},\"oauth_scopes\":{},\"oauth_audience\":{},\"update_notice\":{},\"support_url\":{}},\"mcp\":{\"tool_mode\":{}},\"docs_url\":\"example\"},\"mcp_enabled\":true,\"mcp_url\":\"example\",\"agent_context_enabled\":true,\"agent_context_url\":\"example\",\"relay_enabled\":true,\"platforms\":[\"sdk\"],\"created_at\":\"2024-01-01T00:00:00Z\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, bearerToken: "test-token" });
    const result = await client.projects.get("test-project_id");
    assert.equal(result.ok, true, JSON.stringify(result));
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/projects/test-project_id");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("projects.delete DELETE /projects/{project_id}", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"deleted\":true}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, bearerToken: "test-token" });
    const result = await client.projects.delete("test-project_id");
    assert.equal(result.ok, true, JSON.stringify(result));
    const request = mock.requests[0];
    assert.equal(request.method, "DELETE");
    assert.equal(request.path.split("?")[0], "/projects/test-project_id");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("projects.update PATCH /projects/{project_id}", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"example\",\"object\":\"project\",\"name\":\"example\",\"spec_url\":\"example\",\"source\":{\"kind\":\"url\",\"url\":\"example\",\"repo\":\"example\",\"path\":\"example\"},\"destination\":{\"repo\":\"example\",\"directory\":\"example\"},\"languages\":[\"typescript\"],\"destinations\":{},\"package_names\":{},\"auto_regen\":true,\"package_name\":\"example\",\"spec_patches\":[{\"op\":\"set\",\"path\":\"example\",\"value\":{},\"to\":\"example\",\"reason\":\"example\"}],\"config\":{\"globals\":[{}],\"retries\":{\"max_retries\":{},\"statuses\":{},\"initial_delay_ms\":{},\"max_delay_ms\":{},\"retry_non_idempotent\":{},\"disabled\":{},\"operations\":{}},\"pagination\":{},\"cli\":{\"whoami_operation\":{},\"oauth_client_id\":{},\"oauth_scopes\":{},\"oauth_audience\":{},\"update_notice\":{},\"support_url\":{}},\"mcp\":{\"tool_mode\":{}},\"docs_url\":\"example\"},\"mcp_enabled\":true,\"mcp_url\":\"example\",\"agent_context_enabled\":true,\"agent_context_url\":\"example\",\"relay_enabled\":true,\"platforms\":[\"sdk\"],\"created_at\":\"2024-01-01T00:00:00Z\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, bearerToken: "test-token" });
    const result = await client.projects.update("test-project_id", {});
    assert.equal(result.ok, true, JSON.stringify(result));
    const request = mock.requests[0];
    assert.equal(request.method, "PATCH");
    assert.equal(request.path.split("?")[0], "/projects/test-project_id");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("projects.listGenerations GET /projects/{project_id}/generations", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"data\":[{\"id\":\"example\",\"object\":\"generation\",\"files_omitted\":true,\"files_index\":[{\"path\":\"example\",\"bytes\":1}],\"project_id\":\"example\",\"status\":\"succeeded\",\"trigger\":\"manual\",\"language\":\"typescript\",\"meta\":{\"title\":\"example\",\"version\":\"example\",\"spec_format\":\"openapi\",\"oas_version\":\"example\",\"converted\":true,\"package_name\":\"example\",\"client_name\":\"example\",\"targets\":[\"sdk\"],\"resource_count\":1,\"operation_count\":1,\"schema_count\":1,\"paginated_operation_count\":1,\"omitted_operation_count\":1,\"pr_url\":\"example\",\"pr_number\":1,\"file_count\":1,\"total_lines\":1},\"warnings\":[\"example\"],\"files\":[{\"path\":\"example\",\"content\":\"example\"}],\"error\":\"example\",\"created_at\":\"2024-01-01T00:00:00Z\"}]}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, bearerToken: "test-token" });
    const result = await client.projects.listGenerations("test-project_id", undefined);
    assert.equal(result.ok, true, JSON.stringify(result));
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/projects/test-project_id/generations");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("projects.generate POST /projects/{project_id}/generations", async () => {
  const mock = await startMock({ status: 201, contentType: "application/json", body: "{\"data\":[{\"id\":{},\"object\":{},\"files_omitted\":{},\"files_index\":{},\"project_id\":{},\"status\":{},\"trigger\":{},\"language\":{},\"meta\":{},\"warnings\":{},\"files\":{},\"error\":{},\"created_at\":{}}]}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, bearerToken: "test-token" });
    const result = await client.projects.generate("test-project_id");
    assert.equal(result.ok, true, JSON.stringify(result));
    const request = mock.requests[0];
    assert.equal(request.method, "POST");
    assert.equal(request.path.split("?")[0], "/projects/test-project_id/generations");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});
