// typeship — generated smoke tests for the specs resource.
// Generated by typeship — https://typeship.dev
import test from "node:test";
import assert from "node:assert/strict";
import { TypeshipClient } from "../dist/index.js";
import { startMock } from "./helper.mjs";

test("specs.get GET /specs/{spec_id}", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"spec_2p8m4q7k1v9d6h3c\",\"object\":\"spec\",\"project_id\":\"prj_4f8k2m7x9q1v6b3n\",\"source\":{\"type\":\"url\",\"url\":{\"url\":\"https://example.com\",\"headers_configured\":true}},\"format\":\"openapi\",\"patches\":[{\"op\":\"remove\",\"path\":\"/components/schemas/Legacy\"}],\"graphql\":{\"endpoint\":\"https://example.com\",\"environments\":[{\"name\":\"example\",\"url\":\"https://example.com\"}],\"auth\":\"bearer\",\"api_key_header\":\"example\",\"title\":\"example\",\"scalars\":{}},\"diagnostic_policy\":{\"fail_on\":\"never\",\"only_new\":true,\"suppressions\":[]},\"revision_latest_id\":\"srev_6m1q8v4k2p9d7h3c\",\"created_at\":\"2024-01-01T00:00:00Z\",\"updated_at\":\"2024-01-01T00:00:00Z\",\"request_id\":\"req_3k8m1v6q9p2d7h4c\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.specs.get("test-spec_id");
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/specs/test-spec_id");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("specs.update PATCH /specs/{spec_id}", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"spec_2p8m4q7k1v9d6h3c\",\"object\":\"spec\",\"project_id\":\"prj_4f8k2m7x9q1v6b3n\",\"source\":{\"type\":\"url\",\"url\":{\"url\":\"https://example.com\",\"headers_configured\":true}},\"format\":\"openapi\",\"patches\":[{\"op\":\"remove\",\"path\":\"/components/schemas/Legacy\"}],\"graphql\":{\"endpoint\":\"https://example.com\",\"environments\":[{\"name\":\"example\",\"url\":\"https://example.com\"}],\"auth\":\"bearer\",\"api_key_header\":\"example\",\"title\":\"example\",\"scalars\":{}},\"diagnostic_policy\":{\"fail_on\":\"never\",\"only_new\":true,\"suppressions\":[]},\"revision_latest_id\":\"srev_6m1q8v4k2p9d7h3c\",\"created_at\":\"2024-01-01T00:00:00Z\",\"updated_at\":\"2024-01-01T00:00:00Z\",\"request_id\":\"req_3k8m1v6q9p2d7h4c\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.specs.update("test-spec_id", {"source":{"type":"url","url":{"url":"https://example.com","headers":{}}},"patches":[{"op":"remove","path":"/components/schemas/Legacy"}],"graphql":{"endpoint":"https://example.com","environments":[{"name":"example","url":"https://example.com"}],"auth":"bearer","api_key_header":"example","title":"example","scalars":{}},"diagnostic_policy":{"fail_on":"never","only_new":true,"suppressions":[]}}, undefined);
    const request = mock.requests[0];
    assert.equal(request.method, "PATCH");
    assert.equal(request.path.split("?")[0], "/specs/test-spec_id");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("specs.refresh POST /specs/{spec_id}/refresh", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"spec_2p8m4q7k1v9d6h3c\",\"object\":\"spec\",\"project_id\":\"prj_4f8k2m7x9q1v6b3n\",\"source\":{\"type\":\"url\",\"url\":{\"url\":\"https://example.com\",\"headers_configured\":true}},\"format\":\"openapi\",\"patches\":[{\"op\":\"remove\",\"path\":\"/components/schemas/Legacy\"}],\"graphql\":{\"endpoint\":\"https://example.com\",\"environments\":[{\"name\":\"example\",\"url\":\"https://example.com\"}],\"auth\":\"bearer\",\"api_key_header\":\"example\",\"title\":\"example\",\"scalars\":{}},\"diagnostic_policy\":{\"fail_on\":\"never\",\"only_new\":true,\"suppressions\":[]},\"revision_latest_id\":\"srev_6m1q8v4k2p9d7h3c\",\"created_at\":\"2024-01-01T00:00:00Z\",\"updated_at\":\"2024-01-01T00:00:00Z\",\"request_id\":\"req_3k8m1v6q9p2d7h4c\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.specs.refresh("test-spec_id", undefined);
    const request = mock.requests[0];
    assert.equal(request.method, "POST");
    assert.equal(request.path.split("?")[0], "/specs/test-spec_id/refresh");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});
