// typeship — generated smoke tests for the specRevisions resource.
// Generated by typeship — https://typeship.dev
import test from "node:test";
import assert from "node:assert/strict";
import { TypeshipClient } from "../dist/index.js";
import { startMock } from "./helper.mjs";

test("specRevisions.list GET /spec-revisions", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"data\":[{\"id\":\"srev_6m1q8v4k2p9d7h3c\",\"object\":\"spec_revision\",\"project_id\":\"prj_4f8k2m7x9q1v6b3n\",\"spec_id\":\"spec_2p8m4q7k1v9d6h3c\",\"format\":\"openapi\",\"file_count\":1,\"sha256\":\"9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08\",\"size_bytes\":1,\"source\":{\"type\":\"url\",\"url\":{\"url\":\"https://example.com\"}},\"diagnostic_summary\":{\"status\":\"passed\",\"error_count\":1,\"warning_count\":1,\"suggestion_count\":1,\"blocking_count\":1,\"baseline_spec_revision_id\":\"srev_6m1q8v4k2p9d7h3c\"},\"diagnostics\":[{\"id\":\"example\",\"object\":\"diagnostic\",\"blocking\":true,\"introduced\":true,\"severity\":\"error\",\"category\":\"correctness\",\"title\":\"example\",\"message\":\"example\",\"surfaces\":[\"api\"],\"owner_decision_required\":true,\"locations\":[{\"file_path\":\"example\",\"file_id\":\"file_4k8m2v7q1p9d5h6c\",\"path\":\"example\",\"operation\":\"example\",\"evidence\":\"example\"}],\"fix\":{\"title\":\"example\",\"type\":\"spec_patch\",\"patches\":[{\"op\":\"remove\",\"path\":\"/components/schemas/Legacy\"}],\"instructions\":\"example\"},\"authoring_brief\":\"example\"}],\"patch_diagnostics\":[{\"code\":\"unsupported_format\",\"message\":\"example\"}],\"created_at\":\"2024-01-01T00:00:00Z\",\"request_id\":\"req_3k8m1v6q9p2d7h4c\"}]}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.specRevisions.list(undefined);
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/spec-revisions");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("specRevisions.get GET /spec-revisions/{spec_revision_id}", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"id\":\"srev_6m1q8v4k2p9d7h3c\",\"object\":\"spec_revision\",\"project_id\":\"prj_4f8k2m7x9q1v6b3n\",\"spec_id\":\"spec_2p8m4q7k1v9d6h3c\",\"format\":\"openapi\",\"file_count\":1,\"sha256\":\"9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08\",\"size_bytes\":1,\"source\":{\"type\":\"url\",\"url\":{\"url\":\"https://example.com\"}},\"diagnostic_summary\":{\"status\":\"passed\",\"error_count\":1,\"warning_count\":1,\"suggestion_count\":1,\"blocking_count\":1,\"baseline_spec_revision_id\":\"srev_6m1q8v4k2p9d7h3c\"},\"diagnostics\":[{\"id\":\"example\",\"object\":\"diagnostic\",\"blocking\":true,\"introduced\":true,\"severity\":\"error\",\"category\":\"correctness\",\"title\":\"example\",\"message\":\"example\",\"surfaces\":[\"api\"],\"owner_decision_required\":true,\"locations\":[{\"file_path\":\"example\",\"file_id\":\"file_4k8m2v7q1p9d5h6c\",\"path\":\"example\",\"operation\":\"example\",\"evidence\":\"example\"}],\"fix\":{\"title\":\"example\",\"type\":\"spec_patch\",\"patches\":[{\"op\":\"remove\",\"path\":\"/components/schemas/Legacy\"}],\"instructions\":\"example\"},\"authoring_brief\":\"example\"}],\"patch_diagnostics\":[{\"code\":\"unsupported_format\",\"message\":\"example\"}],\"created_at\":\"2024-01-01T00:00:00Z\",\"request_id\":\"req_3k8m1v6q9p2d7h4c\"}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.specRevisions.get("test-spec_revision_id", undefined);
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/spec-revisions/test-spec_revision_id");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("specRevisions.listFiles GET /spec-revisions/{spec_revision_id}/files", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"data\":[{\"id\":\"file_4k8m2v7q1p9d5h6c\",\"object\":\"file\",\"path\":\"example\",\"size_bytes\":1,\"sha256\":\"example\",\"encoding\":\"utf8\",\"mode\":\"100644\",\"created_at\":\"2024-01-01T00:00:00Z\",\"role\":\"entrypoint\"}]}" });
  try {
    const client = new TypeshipClient({ baseUrl: mock.url, credentials: {"apiKey":"test-token"} });
    const result = await client.specRevisions.listFiles("test-spec_revision_id", undefined);
    const request = mock.requests[0];
    assert.equal(request.method, "GET");
    assert.equal(request.path.split("?")[0], "/spec-revisions/test-spec_revision_id/files");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});
