/**
 * Auto-pagination. Generated by typeship — https://typeship.dev
 *
 * List operations return a PagePromise: `await` it for one page (a typed
 * ApiResult), or `for await` it to stream every item across every page.
 */

import {
  HttpCore,
  type ApiResult,
  type CoreRequest,
  type ResponseMeta,
} from "./http.js";

export interface PageConfig {
  style: "cursor" | "cursorFromLastId" | "page" | "offset";
  /** Response field holding the item array ("data", "items", …). */
  itemsField: string;
  cursorParam?: string;
  /** Dot-path into the response body ("next_cursor", "meta.next_cursor"). */
  nextCursorField?: string;
  hasMoreField?: string;
  /** cursorFromLastId: item field whose value seeds the next request. */
  idField?: string;
  pageParam?: string;
  offsetParam?: string;
  limitParam?: string;
}

type FetchPage<Item, E> = (
  query: Record<string, unknown>,
) => Promise<ApiResult<Page<Item, E>, E>>;

export class Page<Item, E = unknown> {
  private readonly fetchPage: FetchPage<Item, E>;
  private readonly config: PageConfig;
  private readonly params: Record<string, unknown>;
  readonly body: unknown;
  readonly response: ResponseMeta;

  constructor(
    fetchPage: FetchPage<Item, E>,
    config: PageConfig,
    params: Record<string, unknown>,
    body: unknown,
    response: ResponseMeta,
  ) {
    this.fetchPage = fetchPage;
    this.config = config;
    this.params = params;
    this.body = body;
    this.response = response;
  }

  get items(): Item[] {
    const value = getPath(this.body, this.config.itemsField);
    return Array.isArray(value) ? (value as Item[]) : [];
  }

  hasNextPage(): boolean {
    return this.nextPageParams() !== null;
  }

  nextPageParams(): Record<string, unknown> | null {
    const { config, params } = this;
    const items = this.items;

    if (config.hasMoreField !== undefined) {
      const hasMore = getPath(this.body, config.hasMoreField);
      if (hasMore === false) return null;
    }

    switch (config.style) {
      case "cursor": {
        const next = getPath(this.body, config.nextCursorField!);
        if (next === undefined || next === null || next === "") return null;
        if (next === params[config.cursorParam!]) return null;
        return { ...params, [config.cursorParam!]: next };
      }
    }
    return null;
  }

  /** Fetch the next page, or null when this is the last one. Throws the typed error on failure. */
  async getNextPage(): Promise<Page<Item, E> | null> {
    const next = this.nextPageParams();
    if (next === null) return null;
    const result = await this.fetchPage(next);
    if (!result.ok) {
      throw result.error instanceof Error ? result.error : new Error(String(result.error));
    }
    return result.data;
  }

  /** Iterate every item on this page and all following pages. */
  async *[Symbol.asyncIterator](): AsyncIterator<Item, void, undefined> {
    let page: Page<Item, E> | null = this;
    while (page !== null) {
      for (const item of page.items) yield item;
      page = await page.getNextPage();
    }
  }

  private looksLikeMore(items: Item[]): boolean {
    if (items.length === 0) return false;
    if (this.config.limitParam !== undefined) {
      const limit = Number(this.params[this.config.limitParam]);
      if (Number.isFinite(limit) && limit > 0) return items.length >= limit;
    }
    // Without a has_more signal or an explicit limit, an empty page is the
    // only reliable stop condition.
    return true;
  }
}

/**
 * Awaitable (one page, as a typed ApiResult) and async-iterable (all items,
 * all pages). Iteration throws the operation's typed error union on failure.
 */
export class PagePromise<Item, E> implements PromiseLike<ApiResult<Page<Item, E>, E>>, AsyncIterable<Item> {
  private readonly first: Promise<ApiResult<Page<Item, E>, E>>;
  constructor(first: Promise<ApiResult<Page<Item, E>, E>>) {
    this.first = first;
  }

  then<R1 = ApiResult<Page<Item, E>, E>, R2 = never>(
    onfulfilled?: ((value: ApiResult<Page<Item, E>, E>) => R1 | PromiseLike<R1>) | null,
    onrejected?: ((reason: unknown) => R2 | PromiseLike<R2>) | null,
  ): Promise<R1 | R2> {
    return this.first.then(onfulfilled, onrejected);
  }

  async *[Symbol.asyncIterator](): AsyncIterator<Item, void, undefined> {
    const result = await this.first;
    if (!result.ok) {
      throw result.error instanceof Error ? result.error : new Error(String(result.error));
    }
    yield* result.data;
  }
}

export function paginate<Item, E>(
  core: HttpCore,
  req: CoreRequest,
  config: PageConfig,
): PagePromise<Item, E> {
  const isGraphql = false
  ;
  const fetchPage: FetchPage<Item, E> = async (params) => {
    let nextReq: CoreRequest = { ...req, query: params };
    const result = await core.request<unknown, E>(nextReq);
    if (!result.ok) return result;
    const page = new Page<Item, E>(fetchPage, config, params, result.data, result.response);
    return { ok: true, data: page, response: result.response };
  };
  const initial: Record<string, unknown> = {};
  let seed = req.query ?? {};
  for (const [k, v] of Object.entries(seed)) {
    if (v !== undefined) initial[k] = v;
  }
  return new PagePromise<Item, E>(fetchPage(initial));
}

function getPath(body: unknown, path: string): unknown {
  let node: unknown = body;
  for (const key of path.split(".")) {
    if (typeof node !== "object" || node === null) return undefined;
    node = (node as Record<string, unknown>)[key];
  }
  return node;
}
