// typeship — typed error classes.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { ApiError, type ResponseMeta } from "./core/http.js";
import type { ErrorModel } from "./types.js";

export { ApiError, GraphQLRequestError, TransportError, UnexpectedApiError, ValidationError, type Violation, unwrap } from "./core/http.js";

/**
 * Missing, invalid, expired, or revoked credentials.
 * Raised for HTTP 401 responses.
 */
export class UnauthorizedError extends ApiError<401, ErrorModel> {
  constructor(body: ErrorModel, response: ResponseMeta) {
    super("Missing, invalid, expired, or revoked credentials.", 401, body, response);
  }
}

/**
 * The credentials are valid but cannot act on the requested organization.
 * Raised for HTTP 403 responses.
 */
export class ForbiddenError extends ApiError<403, ErrorModel> {
  constructor(body: ErrorModel, response: ResponseMeta) {
    super("The credentials are valid but cannot act on the requested organization.", 403, body, response);
  }
}

/**
 * Spec exceeds the 10MB limit.
 * Raised for HTTP 413 responses.
 */
export class PayloadTooLargeError extends ApiError<413, ErrorModel> {
  constructor(body: ErrorModel, response: ResponseMeta) {
    super("Spec exceeds the 10MB limit.", 413, body, response);
  }
}

/**
 * The spec could not be understood.
 * Raised for HTTP 422 responses.
 */
export class UnprocessableEntityError extends ApiError<422, ErrorModel> {
  constructor(body: ErrorModel, response: ResponseMeta) {
    super("The spec could not be understood.", 422, body, response);
  }
}

/**
 * Too many requests. Wait for Retry-After before retrying.
 * Raised for HTTP 429 responses.
 */
export class RateLimitedError extends ApiError<429, ErrorModel> {
  constructor(body: ErrorModel, response: ResponseMeta) {
    super("Too many requests. Wait for Retry-After before retrying.", 429, body, response);
  }
}

/**
 * Unexpected error.
 * Raised for "default" responses.
 */
export class ApiResponseError extends ApiError<number, ErrorModel> {
  constructor(body: ErrorModel, response: ResponseMeta) {
    super("Unexpected error.", response.status, body, response);
  }
}

/**
 * The cursor is malformed.
 * Raised for HTTP 400 responses.
 */
export class BadRequestError extends ApiError<400, ErrorModel> {
  constructor(body: ErrorModel, response: ResponseMeta) {
    super("The cursor is malformed.", 400, body, response);
  }
}

/**
 * The plan does not include another project or the requested output configuration.
 * Raised for HTTP 402 responses.
 */
export class PaymentRequiredError extends ApiError<402, ErrorModel> {
  constructor(body: ErrorModel, response: ResponseMeta) {
    super("The plan does not include another project or the requested output configuration.", 402, body, response);
  }
}

/**
 * No such resource in this account.
 * Raised for HTTP 404 responses.
 */
export class NotFoundError extends ApiError<404, ErrorModel> {
  constructor(body: ErrorModel, response: ResponseMeta) {
    super("No such resource in this account.", 404, body, response);
  }
}

/**
 * Generation or pull-request setup failed unexpectedly.
 * Raised for HTTP 500 responses.
 */
export class InternalServerError extends ApiError<500, ErrorModel> {
  constructor(body: ErrorModel, response: ResponseMeta) {
    super("Generation or pull-request setup failed unexpectedly.", 500, body, response);
  }
}
