// typeship — client entry point.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import { HttpCore, formatDebugEvent, type AuthValue, type DebugEvent, type RequestContext, bearerAuth } from "./core/http";
import { GenerateResource } from "./resources/generate";
import { AccountResource } from "./resources/account";
import { SharesResource } from "./resources/shares";
import { ProjectsResource } from "./resources/projects";
import { GenerationsResource } from "./resources/generations";

/** This package's version, also sent as the `User-Agent`. */
export const VERSION = "1.0.0";
const USER_AGENT = "typeship-sdk/1.0.0 (typeship)";

export interface ClientOptions {
  /** Override the server URL. Default: `https://typeship.dev/api/v1` */
  baseUrl?: string;
  /** Sent as `Authorization: Bearer <token>`. Pass a callback for tokens that expire; it is resolved before every attempt. */
  bearerToken?: string | (() => string | Promise<string>);
  /** Per-attempt timeout in milliseconds. Default: 30000. */
  timeoutMs?: number;
  /** Retries after the first attempt (retryable failures only). Default: 2. */
  maxRetries?: number;
  /** Custom fetch implementation (proxies, testing, instrumentation). */
  fetch?: typeof fetch;
  /** Headers sent with every request. */
  defaultHeaders?: Record<string, string>;
  /** Called before every attempt; mutate context.headers or context.url for logging, tracing, or custom auth. */
  onRequest?: (context: RequestContext) => void | Promise<void>;
  /** Called after every HTTP response, before parsing and retries. Clone the response before reading its body. */
  onResponse?: (response: Response, context: RequestContext) => void | Promise<void>;
  /** Called once per failed call, after retries, with the typed error about to be returned. Observability only. */
  onError?: (error: unknown, request: { method: string; path: string }) => void | Promise<void>;
  /** One redacted line per attempt: true logs to console.error; a function receives the structured DebugEvent for your own logger. Also enabled by the ${envPrefixOf(ir)}_DEBUG=1 env var. Never includes headers or bodies. */
  debug?: boolean | ((event: DebugEvent) => void);
}

/**
 * typeship — v1.0.0
 * 
 * Generate a zero-dependency TypeScript SDK, a CLI, and an MCP server from
 * an OpenAPI spec. Generation and shares need no authentication. Projects
 * and hosted generations require an API key, created in the console and
 * sent as `Authorization: Bearer tsk_...`.
 */
export class TypeshipClient {
  readonly generate: GenerateResource;
  readonly account: AccountResource;
  readonly shares: SharesResource;
  readonly projects: ProjectsResource;
  readonly generations: GenerationsResource;

  constructor(options: ClientOptions = {}) {
    // Identifies this package to the API (ignored by browsers, which
    // control their own User-Agent); override via defaultHeaders.
    const headers: Record<string, AuthValue> = { "User-Agent": USER_AGENT, ...options.defaultHeaders };
    const debugOption = options.debug
      ?? (typeof process !== "undefined" && process.env?.["TYPESHIP_DEBUG"] === "1");
    const debug = typeof debugOption === "function"
      ? debugOption
      : debugOption === true
        ? (event: DebugEvent) => console.error(formatDebugEvent("typeship", event))
        : undefined;
    const query: Record<string, AuthValue> = {};
    if (options.bearerToken !== undefined) headers["Authorization"] = bearerAuth(options.bearerToken);
    const core = new HttpCore({
      baseUrl: options.baseUrl ?? "https://typeship.dev/api/v1",
      headers,
      query,
      fetch: options.fetch ?? fetch,
      timeoutMs: options.timeoutMs ?? 30_000,
      maxRetries: options.maxRetries ?? 2,
      onRequest: options.onRequest,
      onResponse: options.onResponse,
      onError: options.onError,
      debug,
    });
    this.generate = new GenerateResource(core);
    this.account = new AccountResource(core);
    this.shares = new SharesResource(core);
    this.projects = new ProjectsResource(core);
    this.generations = new GenerationsResource(core);
  }
}

export * from "./types";
export * from "./errors";
export {
  formatDebugEvent,
  type ApiResult,
  type AuthValue,
  type DebugEvent,
  type RequestContext,
  type RequestOptions,
  type ResponseMeta,
} from "./core/http";
export { Page, PagePromise } from "./core/pagination";
export * from "./resources/generate";
export * from "./resources/account";
export * from "./resources/shares";
export * from "./resources/projects";
export * from "./resources/generations";
