// typeship — client entry point.
// Generated by typeship — https://typeship.dev

import {
  HttpCore,
  formatDebugEvent,
  type AuthValue,
  type SecurityCredential,
  type DebugEvent,
  type RequestContext,
  bearerAuth,
} from "./core/http.js";
import { DEFS, SCHEMAS } from "./schemas.js";

import { GenerateResource } from "./resources/generate.js";
import { ProjectsResource } from "./resources/projects.js";
import { SpecsResource } from "./resources/specs.js";
import { SpecRevisionsResource } from "./resources/spec-revisions.js";
import { TargetsResource } from "./resources/targets.js";
import { DraftsResource } from "./resources/drafts.js";
import { ReleasesResource } from "./resources/releases.js";
import { DeliveriesResource } from "./resources/deliveries.js";
import { PublicationsResource } from "./resources/publications.js";
import { GenerationsResource } from "./resources/generations.js";
import { FilesResource } from "./resources/files.js";
import { OrganizationResource } from "./resources/organization.js";
import { ApiKeysResource } from "./resources/api-keys.js";

/** This package's version, also sent as the `User-Agent`. */
export const VERSION = "0.25.0";
const USER_AGENT = "@typeship-ax/sdk/0.25.0";

export interface ClientOptions {
  /** Override the server URL. Default: `https://typeship.dev/api/v1` */
  baseUrl?: string;
  /**
   * Sent as `Authorization: Bearer <token>`. Pass a callback for tokens that expire; it is resolved
   * before every attempt.
   */
  bearerToken?: string | (() => string | Promise<string>);
  /**
   * Credentials keyed by the Spec's security scheme names. Only one complete alternative is sent
   * for each operation. Named values take precedence over convenience options.
   */
  credentials?: {
    "apiKey"?: AuthValue;
  };
  /** Per-attempt timeout in milliseconds. Default: 30000. */
  timeoutMs?: number;
  /** Retries after the first attempt (retryable failures only). Default: 2. */
  maxRetries?: number;
  /** Custom fetch implementation (proxies, testing, instrumentation). */
  fetch?: typeof fetch;
  /** Headers sent with every request. */
  defaultHeaders?: Record<string, string>;
  /**
   * Called before every attempt; mutate context.headers or context.url for logging, tracing, or
   * custom auth.
   */
  onRequest?: (context: RequestContext) => void | Promise<void>;
  /**
   * Called after every HTTP response, before parsing and retries. Clone the response before reading
   * its body.
   */
  onResponse?: (response: Response, context: RequestContext) => void | Promise<void>;
  /**
   * Called once per failed call, after retries, with the typed error about to be returned.
   * Observability only.
   */
  onError?: (error: unknown, request: { method: string; path: string }) => void | Promise<void>;
  /**
   * One redacted line per attempt: true logs to console.error; a function receives the structured
   * DebugEvent for your own logger. Also enabled by the TYPESHIP_DEBUG=1 env var. Never includes
   * headers or bodies.
   */
  debug?: boolean | ((event: DebugEvent) => void);
  /**
   * Opt-in zero-dependency runtime validation of JSON bodies against the spec's schemas: true
   * checks requests and responses and throws ValidationError on mismatch; mode "warn" logs via
   * console.warn and lets the call proceed. Catches spec drift the type system can't see.
   */
  validate?: boolean | { requests?: boolean; responses?: boolean; mode?: "throw" | "warn" };
}

/**
 * typeship — v0.25.0
 *
 * Resolve an OpenAPI or GraphQL Spec, diagnose it, and keep every
 * selected CLI, MCP, and SDK Target current.
 *
 * Every operation but one requires a bearer credential: an organization
 * API key from the console, or an OAuth access token carrying the operation's
 * read, generate, or write capability and the organization selected during
 * consent. OAuth grants cannot switch organizations after consent. A browser
 * session is not a credential for this API. The exception is POST /generate,
 * which works anonymously with the free plan's limits.
 *
 * Examples use Parcel, a fictional delivery service. Replace its domains,
 * repository names, and resource identifiers with your own. The hosted
 * petstore Spec is a runnable sample.
 */
export class TypeshipClient {
  readonly generate: GenerateResource;
  readonly projects: ProjectsResource;
  readonly specs: SpecsResource;
  readonly specRevisions: SpecRevisionsResource;
  readonly targets: TargetsResource;
  readonly drafts: DraftsResource;
  readonly releases: ReleasesResource;
  readonly deliveries: DeliveriesResource;
  readonly publications: PublicationsResource;
  readonly generations: GenerationsResource;
  readonly files: FilesResource;
  readonly organization: OrganizationResource;
  readonly apiKeys: ApiKeysResource;

  constructor(options: ClientOptions = {}) {
    // Identifies this package to the API (ignored by browsers, which
    // control their own User-Agent); override via defaultHeaders.
    const headers: Record<string, AuthValue> = { "User-Agent": USER_AGENT, ...options.defaultHeaders };
    const debugOption = options.debug
      ?? (typeof process !== "undefined" && process.env?.["TYPESHIP_DEBUG"] === "1");
    const debug = typeof debugOption === "function"
      ? debugOption
      : debugOption === true
        ? (event: DebugEvent) => console.error(formatDebugEvent("typeship", event))
        : undefined;
    const query: Record<string, AuthValue> = {};
    const authHeaders: Record<string, AuthValue> = {};
    const authQuery: Record<string, AuthValue> = {};

    let bearerCredential: AuthValue | undefined;

    if (options.bearerToken !== undefined) bearerCredential = bearerAuth(options.bearerToken);

    const allowedCredentials = new Set<string>(["apiKey"]);
    for (const name of Object.keys(options.credentials ?? {})) {
      if (!allowedCredentials.has(name)) throw new Error("Unknown security scheme: " + name);
    }
    const credentials: Record<string, SecurityCredential> = Object.create(null);
    {
      const named = options.credentials && Object.hasOwn(options.credentials, "apiKey") ? options.credentials["apiKey"] : undefined;
      const value = named !== undefined ? bearerAuth(named) : bearerCredential;
      if (value !== undefined) credentials["apiKey"] = { headers: { ["Authorization"]: value } };
    }
    const v = options.validate;
    const validate = v
      ? {
          requests: typeof v === "object" ? v.requests !== false : true,
          responses: typeof v === "object" ? v.responses !== false : true,
          mode: (typeof v === "object" && v.mode) || ("throw" as const),
        }
      : undefined;
    const core = new HttpCore({
      baseUrl: options.baseUrl ?? "https://typeship.dev/api/v1",
      headers,
      query,
      credentials,
      fetch: options.fetch ?? fetch,
      timeoutMs: options.timeoutMs ?? 30_000,
      maxRetries: options.maxRetries ?? 2,
      onRequest: options.onRequest,
      onResponse: options.onResponse,
      onError: options.onError,
      debug,
      validate,
      schemas: validate ? SCHEMAS : undefined,
      schemaDefs: validate ? DEFS : undefined,
    });
    this.generate = new GenerateResource(core);
    this.projects = new ProjectsResource(core);
    this.specs = new SpecsResource(core);
    this.specRevisions = new SpecRevisionsResource(core);
    this.targets = new TargetsResource(core);
    this.drafts = new DraftsResource(core);
    this.releases = new ReleasesResource(core);
    this.deliveries = new DeliveriesResource(core);
    this.publications = new PublicationsResource(core);
    this.generations = new GenerationsResource(core);
    this.files = new FilesResource(core);
    this.organization = new OrganizationResource(core);
    this.apiKeys = new ApiKeysResource(core);
  }
}

export * from "./types.js";
export * from "./errors.js";
export {
  formatDebugEvent,
  type AuthValue,
  type DebugEvent,
  type RequestContext,
  type RequestOptions,
  type ResponseMeta,
} from "./core/http.js";
export { Page, PagePromise } from "./core/pagination.js";

export * from "./resources/generate.js";
export * from "./resources/projects.js";
export * from "./resources/specs.js";
export * from "./resources/spec-revisions.js";
export * from "./resources/targets.js";
export * from "./resources/drafts.js";
export * from "./resources/releases.js";
export * from "./resources/deliveries.js";
export * from "./resources/publications.js";
export * from "./resources/generations.js";
export * from "./resources/files.js";
export * from "./resources/organization.js";
export * from "./resources/api-keys.js";
