// typeship — client entry point.
// Generated by typeship — https://typeship.dev — do not edit by hand.

import {
  HttpCore,
  formatDebugEvent,
  type AuthValue,
  type DebugEvent,
  type RequestContext,
  bearerAuth,
} from "./core/http.js";
import { DEFS, SCHEMAS } from "./schemas.js";

import { GenerateResource } from "./resources/generate.js";
import { ProjectsResource } from "./resources/projects.js";
import { DefinitionsResource } from "./resources/definitions.js";
import { TargetsResource } from "./resources/targets.js";
import { GenerationsResource } from "./resources/generations.js";
import { DefinitionRevisionsResource } from "./resources/definition-revisions.js";
import { AccountResource } from "./resources/account.js";
import { ApiKeysResource } from "./resources/api-keys.js";

/** This package's version, also sent as the `User-Agent`. */
export const VERSION = "0.9.0";
const USER_AGENT = "@typeship-ax/sdk/0.9.0 (typeship)";

export interface ClientOptions {
  /** Override the server URL. Default: `https://typeship.dev/api/v1` */
  baseUrl?: string;
  /**
   * Sent as `Authorization: Bearer <token>`. Pass a callback for tokens that expire; it is resolved
   * before every attempt.
   */
  bearerToken?: string | (() => string | Promise<string>);
  /** Per-attempt timeout in milliseconds. Default: 30000. */
  timeoutMs?: number;
  /** Retries after the first attempt (retryable failures only). Default: 2. */
  maxRetries?: number;
  /** Custom fetch implementation (proxies, testing, instrumentation). */
  fetch?: typeof fetch;
  /** Headers sent with every request. */
  defaultHeaders?: Record<string, string>;
  /**
   * Called before every attempt; mutate context.headers or context.url for logging, tracing, or
   * custom auth.
   */
  onRequest?: (context: RequestContext) => void | Promise<void>;
  /**
   * Called after every HTTP response, before parsing and retries. Clone the response before reading
   * its body.
   */
  onResponse?: (response: Response, context: RequestContext) => void | Promise<void>;
  /**
   * Called once per failed call, after retries, with the typed error about to be returned.
   * Observability only.
   */
  onError?: (error: unknown, request: { method: string; path: string }) => void | Promise<void>;
  /**
   * One redacted line per attempt: true logs to console.error; a function receives the structured
   * DebugEvent for your own logger. Also enabled by the SDK_DEBUG=1 env var. Never includes headers
   * or bodies.
   */
  debug?: boolean | ((event: DebugEvent) => void);
  /**
   * Opt-in zero-dependency runtime validation of JSON bodies against the spec's schemas: true
   * checks requests and responses and returns a ValidationError on mismatch (as the ApiResult
   * error, never thrown); mode "warn" logs via console.warn and lets the call proceed. Catches spec
   * drift the type system can't see.
   */
  validate?: boolean | { requests?: boolean; responses?: boolean; mode?: "throw" | "warn" };
}

/**
 * typeship — v0.9.0
 *
 * Resolve an OpenAPI or GraphQL Definition, diagnose it, and keep every
 * selected SDK, CLI, and MCP Target current.
 *
 * Every operation but one requires a bearer credential: an organization
 * API key from the console, or an OAuth access token carrying the operation's
 * read, generate, or write capability and the organization selected during
 * consent. OAuth grants cannot switch organizations after consent. A browser
 * session is not a credential for this API. The exception is POST /generate,
 * which works anonymously with the free plan's limits.
 */
export class TypeshipClient {
  readonly generate: GenerateResource;
  readonly projects: ProjectsResource;
  readonly definitions: DefinitionsResource;
  readonly targets: TargetsResource;
  readonly generations: GenerationsResource;
  readonly definitionRevisions: DefinitionRevisionsResource;
  readonly account: AccountResource;
  readonly apiKeys: ApiKeysResource;

  constructor(options: ClientOptions = {}) {
    // Identifies this package to the API (ignored by browsers, which
    // control their own User-Agent); override via defaultHeaders.
    const headers: Record<string, AuthValue> = { "User-Agent": USER_AGENT, ...options.defaultHeaders };
    const debugOption = options.debug
      ?? (typeof process !== "undefined" && process.env?.["SDK_DEBUG"] === "1");
    const debug = typeof debugOption === "function"
      ? debugOption
      : debugOption === true
        ? (event: DebugEvent) => console.error(formatDebugEvent("sdk", event))
        : undefined;
    const query: Record<string, AuthValue> = {};
    if (options.bearerToken !== undefined) headers["Authorization"] = bearerAuth(options.bearerToken);
    const v = options.validate;
    const validate = v
      ? {
          requests: typeof v === "object" ? v.requests !== false : true,
          responses: typeof v === "object" ? v.responses !== false : true,
          mode: (typeof v === "object" && v.mode) || ("throw" as const),
        }
      : undefined;
    const core = new HttpCore({
      baseUrl: options.baseUrl ?? "https://typeship.dev/api/v1",
      headers,
      query,
      fetch: options.fetch ?? fetch,
      timeoutMs: options.timeoutMs ?? 30_000,
      maxRetries: options.maxRetries ?? 2,
      onRequest: options.onRequest,
      onResponse: options.onResponse,
      onError: options.onError,
      debug,
      validate,
      schemas: validate ? SCHEMAS : undefined,
      schemaDefs: validate ? DEFS : undefined,
    });
    this.generate = new GenerateResource(core);
    this.projects = new ProjectsResource(core);
    this.definitions = new DefinitionsResource(core);
    this.targets = new TargetsResource(core);
    this.generations = new GenerationsResource(core);
    this.definitionRevisions = new DefinitionRevisionsResource(core);
    this.account = new AccountResource(core);
    this.apiKeys = new ApiKeysResource(core);
  }
}

export * from "./types.js";
export * from "./errors.js";
export {
  formatDebugEvent,
  type ApiResult,
  type AuthValue,
  type DebugEvent,
  type RequestContext,
  type RequestOptions,
  type ResponseMeta,
} from "./core/http.js";
export { Page, PagePromise } from "./core/pagination.js";

export * from "./resources/generate.js";
export * from "./resources/projects.js";
export * from "./resources/definitions.js";
export * from "./resources/targets.js";
export * from "./resources/generations.js";
export * from "./resources/definition-revisions.js";
export * from "./resources/account.js";
export * from "./resources/api-keys.js";
