#!/usr/bin/env node
// typeship — MCP server. Generated by typeship — https://typeship.dev
// Two transports, zero dependencies:
//   node mcp.js            stdio (newline-delimited JSON-RPC 2.0)
//   node mcp.js --http     Streamable HTTP on PORT (default 3000)
// handleHttp() is exported for serverless/worker runtimes.
// In HTTP mode an incoming Authorization header is forwarded to the
// upstream API (per-request passthrough); stdio resolves auth from the
// environment, then from credentials/config saved by the CLI's `login`
// and `config` commands (same files, so one login covers both bins).

import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { TypeshipClient, formatDebugEvent, type DebugEvent } from "./index.js";
import { GLOBALS, OPS, buildArgs, missingRequired, type OpSpec } from "./ops.js";

const BIN = "typeship";
const SERVER_NAME = "typeship-mcp";
const SERVER_VERSION = "1.0.0";
const PROTOCOL_VERSION = "2025-03-26";
const DEFAULT_BASE_URL = "https://typeship.dev/api/v1";
const AUTH_SCALARS: { option: string; flag: string; env: string }[] = [{"option":"bearerToken","flag":"token","env":"TYPESHIP_TOKEN"}];
const BASIC: { envUser: string; envPass: string } | null = null;
const ENVIRONMENTS: Record<string, string> = {};
const DOCS_URL_DEFAULT: string | null = "https://typeship.dev";
/** "meta" collapses per-operation tools into search/read/execute so huge
 * APIs don't flood agent context with hundreds of tools. */
const TOOL_MODE: "operations" | "meta" = "operations";
/** Authorization server for OAuth discovery (RFC 9728), from the spec. */
const OAUTH_ISSUER: string | null = null;

function configDir(): string {
  return join(process.env.XDG_CONFIG_HOME ?? join(homedir(), ".config"), BIN);
}

function readJson<T>(file: string): T | null {
  try {
    return JSON.parse(readFileSync(join(configDir(), file), "utf8")) as T;
  } catch {
    return null;
  }
}

function makeClient(): TypeshipClient {
  const stored = readJson<{
    scalars?: Record<string, string>;
    basic?: { username: string; password: string };
    oauth?: { accessToken: string };
  }>("credentials.json");
  const config = readJson<{ baseUrl?: string; environment?: string }>("config.json");
  const options: Record<string, unknown> = {};
  const baseUrl = process.env["TYPESHIP_BASE_URL"]
    ?? config?.baseUrl
    ?? (config?.environment !== undefined ? ENVIRONMENTS[config.environment] : undefined)
    ?? DEFAULT_BASE_URL ?? undefined;
  if (baseUrl === undefined) {
    process.stderr.write("No base URL: set TYPESHIP_BASE_URL in the MCP server env.\n");
    process.exit(1);
  }
  options.baseUrl = baseUrl;
  for (const a of AUTH_SCALARS) {
    const v = process.env[a.env] ?? stored?.scalars?.[a.option];
    if (v !== undefined) options[a.option] = v;
  }
  if (BASIC) {
    const username = process.env[BASIC.envUser] ?? stored?.basic?.username;
    const password = process.env[BASIC.envPass] ?? stored?.basic?.password;
    if (username !== undefined && password !== undefined) options.basicAuth = { username, password };
  }
  if (options.bearerToken === undefined && stored?.oauth?.accessToken !== undefined) {
    options.bearerToken = stored.oauth.accessToken;
  }
  for (const g of GLOBALS) {
    const value = process.env["TYPESHIP_" + g.envSuffix];
    if (value !== undefined) options[g.option] = value;
  }
  if (process.env["TYPESHIP_DEBUG"] === "1") {
    options.debug = (event: DebugEvent) => process.stderr.write(formatDebugEvent(BIN + "-mcp", event) + "\n");
  }
  return new TypeshipClient(options as never);
}

let clientInstance: TypeshipClient | undefined;
function getClient(): TypeshipClient {
  return (clientInstance ??= makeClient());
}

interface JsonRpcRequest {
  jsonrpc: "2.0";
  id?: number | string | null;
  method: string;
  params?: Record<string, unknown>;
}

const EXECUTE_TOOL = {
  name: "execute",
  description: "Execute any API operation by name. Discover operations with search_docs; read_docs <operation> shows its arguments. Arguments are passed as a JSON object keyed by parameter name.",
  inputSchema: {
    type: "object",
    properties: {
      operation: { type: "string", description: "Operation tool name, e.g. accounts_createAccount" },
      arguments: { type: "object", description: "Operation arguments keyed by parameter name" },
    },
    required: ["operation"],
  },
};

function toolDefinitions(): unknown[] {
  if (TOOL_MODE === "meta") {
    return [
      {
        name: "search_docs",
        description: "Search this API's " + OPS.length + " operations and, when a docs site is configured, its guides. Start here to find the operation you need.",
        inputSchema: { type: "object", properties: { query: { type: "string" } }, required: ["query"] },
      },
      {
        name: "read_docs",
        description: "Read an operation's full reference (arguments, requirements) by tool name, or a docs-site guide page.",
        inputSchema: { type: "object", properties: { page: { type: "string" } }, required: ["page"] },
      },
      EXECUTE_TOOL,
    ];
  }
  return [
    ...OPS.map((op) => ({
      name: op.tool,
      description:
        (op.summary ? op.summary + " — " : "") + op.httpMethod + " " + op.path +
        (op.paginated ? " (paginated: returns one page plus hasMore)" : ""),
      inputSchema: op.select
        ? {
            ...op.inputSchema,
            properties: {
              ...(op.inputSchema.properties as Record<string, unknown>),
              select: { type: "string", description: 'GraphQL selection set override, e.g. "{ id name }"' },
            },
          }
        : op.inputSchema,
    })),
    {
      name: "search_docs",
      description: "Search this API's reference (operations, parameters) and, when a docs site is configured, its guides.",
      inputSchema: { type: "object", properties: { query: { type: "string" } }, required: ["query"] },
    },
    {
      name: "read_docs",
      description: "Read a documentation page: an operation reference (e.g. \"accounts.createAccount\") or a docs-site guide page by name or URL.",
      inputSchema: { type: "object", properties: { page: { type: "string" } }, required: ["page"] },
    },
  ];
}

// ---- docs tools: spec reference + docs-site prose (llms.txt) ---------------

function docsSiteUrl(): string | null {
  const config = readJson<{ docsUrl?: string }>("config.json");
  return config?.docsUrl ?? DOCS_URL_DEFAULT;
}

async function fetchDocs(pathOrFile: string): Promise<string | null> {
  const base = docsSiteUrl();
  const url = /^https?:\/\//.test(pathOrFile)
    ? pathOrFile
    : base === null
      ? null
      : base.replace(/\/+$/, "") + "/" + pathOrFile.replace(/^\/+/, "");
  if (url === null) return null;
  try {
    const response = await fetch(url, {
      headers: { Accept: "text/markdown, text/plain, */*" },
      signal: AbortSignal.timeout(10_000),
    });
    if (!response.ok) return null;
    return await response.text();
  } catch {
    return null;
  }
}

function referenceText(op: OpSpec): string {
  const lines = [
    op.tool + " — " + op.httpMethod + " " + op.path + (op.paginated ? " (paginated)" : ""),
    ...(op.summary ? [op.summary] : []),
    ...(op.description ? ["", op.description.trim()] : []),
  ];
  if (op.params.length > 0) {
    lines.push("", "Arguments:");
    for (const p of op.params) {
      lines.push(
        "  " + p.name + " (" + (p.enum ? p.enum.join("|") : p.type) + (p.required ? ", required" : "") + ")" +
        (p.description ? ": " + p.description.trim().split("\n")[0] : ""),
      );
    }
  }
  return lines.join("\n");
}

async function docsSearch(query: string): Promise<string> {
  const term = query.toLowerCase();
  const sections: string[] = [];
  const refMatches = OPS.filter((op) =>
    (op.tool + " " + op.path + " " + (op.summary ?? "") + " " + (op.description ?? "") + " " +
      op.params.map((p) => p.name).join(" ")).toLowerCase().includes(term));
  if (refMatches.length > 0) {
    sections.push("Reference matches:\n" + refMatches.slice(0, 15).map((op) =>
      "- " + op.tool + ": " + (op.summary ?? op.httpMethod + " " + op.path)).join("\n"));
  }
  const prose = await fetchDocs("llms-full.txt");
  if (prose !== null) {
    let heading = "";
    const proseMatches: string[] = [];
    for (const line of prose.split("\n")) {
      if (/^#{1,3} /.test(line)) heading = line.replace(/^#+ /, "").trim();
      else if (line.toLowerCase().includes(term) && proseMatches.length < 15) {
        proseMatches.push("- [" + heading + "] " + line.trim().slice(0, 160));
      }
    }
    if (proseMatches.length > 0) sections.push("Guide matches:\n" + proseMatches.join("\n"));
  }
  if (sections.length === 0) {
    return "No matches for: " + query + (docsSiteUrl() === null ? " (no docs site configured; only the API reference was searched)" : "");
  }
  return sections.join("\n\n");
}

async function docsRead(page: string): Promise<{ text: string; isError: boolean }> {
  const opMatch = OPS.find((op) => op.tool === page || op.tool.toLowerCase() === page.toLowerCase().replace(/\./g, "_"));
  if (opMatch) return { text: referenceText(opMatch), isError: false };
  let target = page;
  if (!/^https?:\/\//.test(target)) {
    const index = await fetchDocs("llms.txt");
    const linked = index?.match(/\((https?:[^)]+)\)/g)?.map((m) => m.slice(1, -1)) ?? [];
    const hit = linked.find((u) => u.toLowerCase().includes(target.toLowerCase()));
    if (hit !== undefined) target = hit;
  }
  const text = await fetchDocs(target);
  if (text === null) {
    return {
      text: docsSiteUrl() === null
        ? "No docs site is configured for this server, and no operation matches \"" + page + "\"."
        : "Couldn't fetch \"" + page + "\". Use search_docs to find pages.",
      isError: true,
    };
  }
  return { text, isError: false };
}

async function callTool(
  op: OpSpec,
  args: Record<string, unknown>,
  authHeader?: string,
): Promise<{ text: string; isError: boolean }> {
  const values: Record<string, unknown> = {};
  for (const p of op.params) {
    if (args[p.name] !== undefined) values[p.name] = args[p.name];
  }
  const missing = missingRequired(op, values).filter((name) => !(op.bodyStyle === "data" && name === "body" && args.body !== undefined));
  if (missing.length > 0) {
    return { text: "Missing required argument(s): " + missing.join(", "), isError: true };
  }
  const callArgs = buildArgs(
    op,
    values,
    op.bodyStyle === "data" ? args.body : undefined,
    typeof args.select === "string" ? args.select : undefined,
  );
  if (authHeader) {
    callArgs.push({ headers: { Authorization: authHeader } });
  }
  const target = (getClient() as unknown as Record<string, Record<string, (...a: unknown[]) => unknown>>)[op.resource]!;
  try {
    const result = await (target[op.method]!(...callArgs) as Promise<{ ok: boolean; data?: unknown; error?: unknown }>);
    if (result.ok) {
      if (op.paginated) {
        const page = result.data as { items: unknown[]; hasNextPage(): boolean };
        return { text: JSON.stringify({ items: page.items, hasMore: page.hasNextPage() }, null, 2), isError: false };
      }
      return { text: JSON.stringify(result.data ?? { ok: true }, null, 2), isError: false };
    }
    const e = result.error as { name?: string; message?: string; status?: number; body?: unknown };
    return {
      text: JSON.stringify({ error: e?.name ?? "Error", message: e?.message, status: e?.status, body: e?.body }, null, 2),
      isError: true,
    };
  } catch (e) {
    return { text: (e as Error).message ?? "Tool call failed", isError: true };
  }
}

async function handleRpc(
  request: JsonRpcRequest,
  authHeader?: string,
): Promise<Record<string, unknown> | null> {
  const id = request.id ?? null;
  const reply = (result: unknown) => ({ jsonrpc: "2.0", id, result });
  const replyError = (code: number, message: string) => ({ jsonrpc: "2.0", id, error: { code, message } });

  switch (request.method) {
    case "initialize":
      return reply({
        protocolVersion: typeof request.params?.protocolVersion === "string" ? request.params.protocolVersion : PROTOCOL_VERSION,
        capabilities: { tools: {} },
        serverInfo: { name: SERVER_NAME, version: SERVER_VERSION },
      });
    case "ping":
      return reply({});
    case "tools/list":
      return reply({ tools: toolDefinitions() });
    case "tools/call": {
      const name = request.params?.name;
      if (name === "search_docs" || name === "read_docs") {
        const docArgs = (request.params?.arguments ?? {}) as { query?: unknown; page?: unknown };
        if (name === "search_docs") {
          if (typeof docArgs.query !== "string") return replyError(-32602, "search_docs requires a query string");
          return reply({ content: [{ type: "text", text: await docsSearch(docArgs.query) }], isError: false });
        }
        if (typeof docArgs.page !== "string") return replyError(-32602, "read_docs requires a page string");
        const docResult = await docsRead(docArgs.page);
        return reply({ content: [{ type: "text", text: docResult.text }], isError: docResult.isError });
      }
      if (name === "execute") {
        const executeArgs = (request.params?.arguments ?? {}) as { operation?: unknown; arguments?: unknown };
        if (typeof executeArgs.operation !== "string") return replyError(-32602, "execute requires an operation name");
        const wanted = executeArgs.operation;
        const target = OPS.find((o) => o.tool === wanted || o.tool === wanted.replace(/\./g, "_"));
        if (!target) return replyError(-32602, "Unknown operation: " + wanted + ". Use search_docs to find operations.");
        const opArgs = (executeArgs.arguments ?? {}) as Record<string, unknown>;
        const { text, isError } = await callTool(target, opArgs, authHeader);
        return reply({ content: [{ type: "text", text }], isError });
      }
      const op = OPS.find((o) => o.tool === name);
      if (!op) return replyError(-32602, "Unknown tool: " + String(name));
      const args = (request.params?.arguments ?? {}) as Record<string, unknown>;
      const { text, isError } = await callTool(op, args, authHeader);
      return reply({ content: [{ type: "text", text }], isError });
    }
    default:
      if (request.method.startsWith("notifications/")) return null;
      if (request.id === undefined) return null;
      return replyError(-32601, "Method not found: " + request.method);
  }
}

// ---- Streamable HTTP transport ---------------------------------------------

const CORS_HEADERS: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, Mcp-Session-Id, Mcp-Protocol-Version",
};

function protectedResourceMetadata(origin: string): Record<string, unknown> {
  return {
    resource: origin,
    ...(OAUTH_ISSUER ? { authorization_servers: [OAUTH_ISSUER] } : {}),
    bearer_methods_supported: ["header"],
  };
}

/** Fetch-style handler: mount in any runtime (workers, serverless, node). */
export async function handleHttp(request: Request): Promise<Response> {
  const url = new URL(request.url);
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: CORS_HEADERS });
  }
  if (url.pathname.endsWith("/.well-known/oauth-protected-resource")) {
    return new Response(JSON.stringify(protectedResourceMetadata(url.origin)), {
      headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
    });
  }
  if (request.method !== "POST") {
    return new Response(JSON.stringify({ error: "POST JSON-RPC messages to this endpoint." }), {
      status: 405,
      headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
    });
  }

  const authHeader = request.headers.get("authorization") ?? undefined;
  const envHasAuth = AUTH_SCALARS.some((a) => process.env[a.env] !== undefined);
  if (OAUTH_ISSUER && !authHeader && !envHasAuth) {
    return new Response(JSON.stringify({ error: "Authorization required." }), {
      status: 401,
      headers: {
        ...CORS_HEADERS,
        "Content-Type": "application/json",
        "WWW-Authenticate": 'Bearer resource_metadata="' + url.origin + '/.well-known/oauth-protected-resource"',
      },
    });
  }

  let message: JsonRpcRequest;
  try {
    message = (await request.json()) as JsonRpcRequest;
  } catch {
    return new Response(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } }), {
      status: 400,
      headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
    });
  }
  const response = await handleRpc(message, authHeader);
  if (response === null) {
    return new Response(null, { status: 202, headers: CORS_HEADERS });
  }
  return new Response(JSON.stringify(response), {
    headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
  });
}

function startHttp(port: number): void {
  void import("node:http").then(({ createServer }) => {
    createServer((req, res) => {
      let body = "";
      req.on("data", (chunk) => (body += chunk));
      req.on("end", () => {
        void handleHttp(
          new Request("http://localhost:" + port + (req.url ?? "/"), {
            method: req.method,
            headers: Object.fromEntries(
              Object.entries(req.headers).map(([k, v]) => [k, Array.isArray(v) ? v.join(", ") : String(v ?? "")]),
            ),
            ...(req.method === "POST" ? { body } : {}),
          }),
        ).then(async (response) => {
          res.statusCode = response.status;
          response.headers.forEach((value, key) => res.setHeader(key, value));
          res.end(await response.text());
        });
      });
    }).listen(port, () => {
      process.stderr.write(SERVER_NAME + " listening on http://localhost:" + port + "\n");
    });
  });
}

async function startStdio(): Promise<void> {
  // dynamic: node:readline doesn't exist in worker runtimes, and workers
  // never take the stdio path
  const { createInterface } = await import("node:readline");
  const rl = createInterface({ input: process.stdin });
  rl.on("line", (line) => {
    const trimmed = line.trim();
    if (trimmed === "") return;
    let request: JsonRpcRequest;
    try {
      request = JSON.parse(trimmed) as JsonRpcRequest;
    } catch {
      process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } }) + "\n");
      return;
    }
    void handleRpc(request)
      .then((response) => {
        if (response !== null) process.stdout.write(JSON.stringify(response) + "\n");
      })
      .catch((e) => {
        if (request.id !== undefined) {
          process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id: request.id ?? null, error: { code: -32603, message: (e as Error).message ?? "Internal error" } }) + "\n");
        }
      });
  });
  rl.on("close", () => process.exit(0));
}

const invokedDirectly = typeof process.argv[1] === "string" && /mcp\.(js|mjs|ts)$/.test(process.argv[1]);
if (invokedDirectly) {
  const httpFlag = process.argv.indexOf("--http");
  if (httpFlag !== -1) {
    const port = Number(process.argv[httpFlag + 1]) || Number(process.env.PORT) || 3000;
    startHttp(port);
  } else {
    void startStdio();
  }
}
