// typeship — API types.
// Generated by typeship — https://typeship.dev — do not edit by hand.

/** Unique identifier for a project. */
export type ProjectId = string;

/** Unique identifier for a generation. */
export type GenerationId = string;

/** Unique identifier for an immutable specification revision. */
export type SpecRevisionId = string;

/** Identifier used to correlate an API error with Typeship logs. */
export type RequestId = string;

/** Identifies a cursor-paginated collection. */
export type ListObject = "list";

/** One customer-selected output. CLI and MCP include the private TypeScript request runtime they need; that dependency is not a selected or billable TypeScript SDK. */
export const OutputId = {
  TYPESCRIPT_SDK: "typescript-sdk",
  PYTHON_SDK: "python-sdk",
  GO_SDK: "go-sdk",
  CLI: "cli",
  MCP: "mcp",
} as const;
export type OutputId = (typeof OutputId)[keyof typeof OutputId];

export interface UrlSpecInput {
  /**
   * URL of an OpenAPI document, a GraphQL SDL file, or a GraphQL
   * endpoint (introspected automatically). Fetched server-side.
   * Format: uri
   */
  url: string;
  /** Request headers for a protected URL. Sent on the document GET and GraphQL introspection POST, never returned or retained by stateless generation. */
  headers?: Record<string, string>;
}

export interface InlineSpecInput {
  /** Raw spec text (OpenAPI JSON/YAML or GraphQL SDL). Up to 10MB. */
  inline: string;
}

/** The specification for stateless generation, provided as exactly one URL or inline document. */
export type SpecInput = UrlSpecInput | InlineSpecInput;

export interface GenerateRequest {
  spec: SpecInput;
  /** Outputs for one delivery package. Choose one SDK output, or TypeScript SDK, CLI, and MCP in any combination. Linked projects can generate outputs in all ecosystems. */
  outputs: OutputId[];
  /** Registry name for the selected delivery package: an npm package, Python distribution, or Go module path. Defaults to a name derived from the API title. */
  package_name?: string;
  config?: Config;
}

export interface GeneratedFile {
  /** Repo-relative path inside the generated package. */
  path: string;
  content: string;
}

export interface GenerationMeta {
  title: string;
  version: string;
  spec_format?: "openapi" | "graphql";
  /** Detected spec version, "2.0", "3.0", or "3.1". */
  oas_version: string;
  /** True when the input was Swagger 2.0 and was converted. */
  converted?: boolean;
  package_name: string;
  client_name: string;
  /** Customer-selected outputs present in this delivery package. */
  outputs: OutputId[];
  resource_count?: number;
  operation_count?: number;
  schema_count?: number;
  paginated_operation_count?: number;
  /** Operations beyond the plan's endpoint allowance, not generated. */
  omitted_operation_count?: number;
  /** Pull request opened by this regeneration, when one was. */
  pr_url?: string | null;
  pr_number?: number | null;
  /** Whether a destination pull request opened, was unnecessary because the generated tree already matched, or could not be opened. */
  pr_status?: "opened" | "no_changes" | "blocked";
  /** Why the configured destination pull request was not opened. Generation itself still succeeded; fix this action and regenerate. */
  pr_error?: string;
  /** Markdown changelog entry for this regeneration, from the API surface diff. Absent on a first generation or when nothing changed. */
  changelog?: string;
  /** Breaking changes in the diff; removed methods and fields, changed types, inputs that became required. */
  breaking_count?: number;
  /** What the diff was measured against; "destination" means the .typeship/surface.json merged in the destination repository. */
  baseline?: "destination" | "last-generation" | "none";
  /** The package compatibility verdict on the regeneration pull request; failure means breaking changes without a major version bump. */
  package_compatibility?: "success" | "failure";
  /** The verdict in one line, as the commit status describes it. */
  package_compatibility_note?: string;
  /** The package version the destination had before this regeneration. */
  previous_version?: string;
  file_count?: number;
  total_lines?: number;
}

export interface GenerationResult {
  files: GeneratedFile[];
  warnings: string[];
  meta: GenerationMeta;
  limits?: GenerationLimits;
  /** Anonymous, URL-sourced generations only. A link a signed-in person can open to turn this run into a project in their organization (same spec, outputs, and config). Lasts seven days. Null for inline specs; absent on keyed calls. */
  claim?: null | {
    url: string;
    /** Format: date-time */
    expires_at: string;
  };
}

/** Present when the generation was capped: by the free plan, or because the call was anonymous. Absent on uncapped generations. */
export interface GenerationLimits {
  /** How many operations this generation was allowed to include. */
  max_operations: number;
  /** How many operations in the spec were left out. */
  omitted_operations: number;
  reason: "anonymous" | "free_plan";
  /** Anonymous calls only. Where to create an account. */
  signup_url?: string;
  /** Where the cap is lifted. */
  upgrade_url: string;
}

export interface UrlProjectSource {
  kind: "url";
  /**
   * URL fetched for every generation.
   * Format: uri
   */
  url: string;
  /** Whether Typeship has stored write-only request headers for this URL. */
  headers_configured: boolean;
}

export interface GithubProjectSource {
  kind: "github";
  /** GitHub repository in owner/name form. */
  repository: string;
  /** Repository-relative path to the specification. */
  path: string;
}

/** The single source of truth for where a project's specification lives. */
export type ProjectSource = UrlProjectSource | GithubProjectSource;

export interface UrlProjectSourceInput {
  kind: "url";
  /**
   * URL of an OpenAPI document, GraphQL SDL file, or GraphQL endpoint.
   * Format: uri
   */
  url: string;
  /** Request headers for a protected URL. Values are never returned or recorded in revision history. When updating the same URL, omit headers to preserve the stored values or pass null to remove them. Changing the URL without headers clears the old values so a credential is never forwarded to a different source. */
  headers?: Record<string, string> | null;
}

export interface GithubProjectSourceInput {
  kind: "github";
  /** GitHub repository in owner/name form. */
  repository: string;
  /** Repository-relative path to the specification. */
  path: string;
}

export type ProjectSourceInput = UrlProjectSourceInput | GithubProjectSourceInput;

/**
 * A fix applied to the spec before generation. Targets are JSON
 * Pointers into the document. A patch whose target no longer exists is
 * skipped and reported as a warning on the generation, never silently.
 */
export interface SpecPatch {
  op: "set" | "append" | "remove" | "rename";
  /**
   * JSON-Pointer-style path. Pattern segments enable bulk fixes:
   * * (any child), ** (any depth), [key=value] (filter), e.g.
   * /paths/**\/parameters/[name=account_id]/schema/type. Renaming a
   * schema under /components/schemas also rewrites its $refs.
   */
  path: string;
  /** set only; the replacement value. */
  value?: unknown;
  /** rename only; the new key name. */
  to?: string | null;
  reason?: string | null;
}

/** Where regeneration pull requests land. */
export interface Destination {
  /** Defaults to the source repository when the source is a repo. */
  repo?: string | null;
  /** Directory the generated package is written to. */
  directory?: string | null;
}

/** Registry identity and reviewed pull-request destination for one delivery package. */
export interface PackageDelivery {
  /** npm package name, Python distribution name, or Go module path. Null derives a name from the API title. */
  name?: string | null;
  destination?: Destination | null;
}

/** Delivery packages keyed by registry ecosystem. TypeScript SDK, CLI, and MCP share npm delivery without becoming the same output. Python and Go SDKs use their own package ecosystems. */
export interface Packages {
  npm?: PackageDelivery;
  python?: PackageDelivery;
  go?: PackageDelivery;
}

export interface ProjectDestination {
  repo: string | null;
  directory: string | null;
}

export interface ProjectPackageDelivery {
  name: string | null;
  destination: ProjectDestination | null;
}

/** Complete package configuration. All ecosystems are returned even when their output is not selected, so saved delivery settings do not disappear when an output is disabled. */
export interface ProjectPackages {
  npm: ProjectPackageDelivery;
  python: ProjectPackageDelivery;
  go: ProjectPackageDelivery;
}

export interface Project {
  id: ProjectId;
  object: "project";
  name: string;
  source: ProjectSource;
  packages: ProjectPackages;
  /** Regenerate when the spec changes: on every push to the default branch for a repository source, every 30 minutes for a URL source. Off by default: the first generation is always one you asked for. Off means only "generate now" and POST /projects/{project_id}/generations regenerate. */
  auto_regen: boolean;
  spec_patches: SpecPatch[];
  config: Config | null;
  /** Whether the hosted MCP endpoint is on. Requires the MCP output and Enterprise; turning the output off turns this off. */
  mcp_enabled: boolean;
  /** Path of the hosted MCP endpoint while it is on; read-only. */
  mcp_url: string | null;
  /** Whether the webhook relay is on, letting the generated CLI's webhooks listen command mint relay sessions. Requires the cli output and Pro; turning the output off turns this off. */
  relay_enabled: boolean;
  /** First-class generated outputs. Any non-empty combination is valid. Free keeps every selected output current for the first 25 operations in one linked project. On Pro, each selected output is billed once; shared implementation runtimes are included. */
  outputs: OutputId[];
  /** Format: date-time */
  created_at: string;
  /**
   * When the project configuration last changed.
   * Format: date-time
   */
  updated_at: string;
}

export interface CreateProjectRequest {
  name: string;
  source: ProjectSourceInput;
  /** First-class outputs Typeship will keep current for this project. */
  outputs: OutputId[];
  /** Initial package names and destinations. Omitted ecosystems use derived names and no destination. */
  packages?: Packages;
  /**
   * Whether Typeship should regenerate automatically when the source changes.
   * Default: false
   */
  auto_regen?: boolean;
  /** Initial patches. Omit or pass an empty array for none. */
  spec_patches?: SpecPatch[];
  /**
   * Serve this project as a hosted MCP endpoint. Requires the MCP output and Enterprise.
   * Default: false
   */
  mcp_enabled?: boolean;
  /**
   * Enable webhook relay sessions. Requires the CLI output and Pro.
   * Default: false
   */
  relay_enabled?: boolean;
  config?: Config | null;
}

export interface UpdateProjectRequest {
  name?: string;
  source?: ProjectSourceInput;
  /** Replaces the selected outputs; delivered files are not deleted. */
  outputs?: OutputId[];
  /** Replaces package configuration for every ecosystem. Include any existing ecosystem settings you want to keep. */
  packages?: Packages;
  auto_regen?: boolean;
  /** Replaces the full patch list. Pass an empty array to clear it. */
  spec_patches?: SpecPatch[];
  /** Serve this project as a hosted MCP endpoint. Requires the MCP output and Enterprise. */
  mcp_enabled?: boolean;
  /** Enable webhook relay sessions. Requires the CLI output and Pro. */
  relay_enabled?: boolean;
  /** Replaces the entire configuration; pass null to clear it. */
  config?: Config | null;
}

/** The organization an API key belongs to. Members share its projects, keys, and plan; sign-in identity is not part of the API. */
export interface Account {
  id: string;
  object: "account";
  /** The organization's display name. */
  name: string;
  plan: "free" | "pro" | "enterprise";
  /** Format: date-time */
  created_at: string;
}

/** How the generated CLI behaves. Part of Config. */
export interface CliBehavior {
  /** resource.method of a zero-argument GET that the generated CLI's whoami command calls. Overrides auto-detection; a value that matches nothing is reported as a generation warning. */
  whoami_operation?: string | null;
  /** OAuth client id baked into the generated CLI for device-flow login. Without it, login prompts for a pasted credential. */
  oauth_client_id?: string | null;
  /** Scopes requested during device-flow login. Include offline_access if the authorization server gates refresh tokens behind it. */
  oauth_scopes?: string[];
  /** Audience sent with the device-authorization request, for authorization servers that require one to issue API-valid access tokens. */
  oauth_audience?: string | null;
  /** Opt in to a once-a-day registry check that prints an upgrade hint. Off by default; generated code phones nobody unless this is enabled. */
  update_notice?: boolean;
  /** Where the generated CLI's feedback command sends users. GitHub issues/new URLs get a prefilled title and environment details. */
  support_url?: string | null;
  /** Base URL of the browser-approval endpoint pair used by CLI login. The CLI keeps the verifier and receives the credential directly; no key is pasted through a conversation. */
  auth_url?: string | null;
  /** Hosted MCP endpoint installed by the generated CLI instead of launching the package's local stdio server. */
  mcp_url?: string | null;
  /** GitHub owner/name of the skills package the generated CLI offers to install during init. */
  skills_repo?: string | null;
}

/** How the generated MCP server and the hosted endpoint behave. Part of Config. */
export interface McpBehavior {
  /** MCP tool shape. meta collapses per-operation tools into search_docs, read_docs, and execute so large APIs don't flood an agent's context window. Auto considers the serialized tool schemas, switching near 10k tokens or above 100 operations. */
  tool_mode?: "auto" | "operations" | "meta";
  /** Guidance appended to the MCP server's instructions, which agents read once when they connect (server/discover): what to call first, conventions the spec does not state, what not to do. Carried by the package's server and the hosted endpoint alike. */
  instructions?: string | null;
  /** Hand-written MCP tool descriptions keyed by operationId or "METHOD /path". Each replaces the text typeship derives for that operation (summary, first sentence, method and path, deprecation and auth notes). For flows the spec cannot describe, such as a multi-step upload. Keys that match no operation are reported as generation warnings. */
  tool_descriptions?: Record<string, string>;
}

/** Published-package metadata the API spec does not own. Use version only when the client intentionally releases on a different cadence from info.version; repository is derived from each destination. */
export interface PackageBehavior {
  /** Semantic version for the generated packages. Defaults to info.version. */
  version?: string | null;
  /** Homepage written into registry metadata. */
  homepage?: string | null;
  /** SPDX identifier written into registry metadata. Defaults to info.license. */
  license?: string | null;
  /** Exact LICENSE file contents. Supply this for licences the engine does not build in; MIT is built in when copyright is also set. */
  license_text?: string | null;
  /** Copyright line used in generated license files. */
  copyright?: string | null;
  /** CLI executable name when it differs from the npm package name. */
  bin_name?: string | null;
  /** Go identifier when the destination repository name is unsuitable. */
  go_package_name?: string | null;
  /** Official MCP registry name written into package.json. */
  mcp_name?: string | null;
}

/** Everything typeship needs beyond the spec, in one object: generation customization (globals, retries, pagination) and how the generated tooling behaves (cli, mcp, package, docs_url). Plain configuration. typeship never requires vendor extensions inside the spec itself. The same shape is accepted on a project and on POST /generate. */
export interface Config {
  /** Wire names of query/header parameters that become settable once on the generated client and auto-apply to every operation that accepts them; per-call values win. Names that match nothing are reported as generation warnings. */
  globals?: string[];
  retries?: RetryTuning;
  /** Per-operation pagination control, keyed by operationId or "METHOD /path". Unmatched keys are reported as generation warnings. */
  pagination?: Record<string, PaginationRule | boolean>;
  graphql?: GraphqlSettings;
  cli?: CliBehavior;
  mcp?: McpBehavior;
  package?: PackageBehavior;
  /** The API's documentation site. Read through its llms.txt by the generated CLI's docs command, the MCP server's docs tools, and the package's AGENTS.md. Defaults to the spec's externalDocs URL. */
  docs_url?: string | null;
}

/** What a GraphQL schema cannot say about itself. Ignored for OpenAPI specs. */
export interface GraphqlSettings {
  /**
   * The URL every request is POSTed to; the generated client's default baseUrl. Defaults to the URL the schema was fetched from. Without either, baseUrl is a required client option.
   * Format: uri
   */
  endpoint?: string;
  /** Named endpoints (sandbox, production). Each becomes a client environment; the first is the default unless endpoint is set. */
  environments?: Array<{
    name: string;
    /** Format: uri */
    url: string;
  }>;
  /**
   * How requests authenticate. bearer sends Authorization: Bearer; basic is for key-pair APIs (public key as username, private key as password); api_key sends a header named by api_key_header; none generates no auth option.
   * Default: "bearer"
   */
  auth?: "bearer" | "basic" | "api_key" | "none";
  /** Header carrying the key when auth is api_key. Required for that mode; Typeship does not invent a vendor-specific header name. */
  api_key_header?: string;
  /** The API's name; drives the package and client names ("Braintree" gives braintree and BraintreeClient). Defaults to a name derived from the endpoint's host. */
  title?: string;
  /** JSON representation of each custom scalar, keyed by GraphQL scalar name. Unmapped scalars generate as the language's untyped JSON value and produce a warning. Unmatched keys warn. */
  scalars?: Record<string, "string" | "integer" | "number" | "boolean" | "json">;
}

/** Retry behavior. Top-level fields adjust every operation; operations maps operationId or "METHOD /path" keys to per-operation overrides. */
export interface RetryTuning {
  max_retries?: number;
  /** Replaces the default retryable set (408, 429, 500, 502, 503, 504). */
  statuses?: number[];
  initial_delay_ms?: number;
  max_delay_ms?: number;
  /** Also retry non-idempotent methods (POST/PATCH). */
  retry_non_idempotent?: boolean;
  /** Shorthand for max_retries 0. */
  disabled?: boolean;
  operations?: Record<string, RetryTuning>;
}

export interface PaginationRule {
  /** Default: "cursor" */
  style?: "cursor" | "cursorFromLastId" | "page" | "offset";
  /** Response field holding the item array. */
  items_field: string;
  cursor_param?: string;
  next_cursor_field?: string;
  has_more_field?: string;
  id_field?: string;
  page_param?: string;
  offset_param?: string;
  limit_param?: string;
}

export interface FileStub {
  path: string;
  bytes: number;
}

export interface Generation {
  id: GenerationId;
  object: "generation";
  /** Present and true when the generated output was too large to inline; files_index lists paths, fetched one at a time via GET /generations/{generation_id}/file. */
  files_omitted?: boolean;
  files_index?: FileStub[];
  project_id: ProjectId;
  status: "succeeded" | "failed";
  trigger: "manual" | "webhook" | "poll" | "preview";
  /** Language this run generated. Null on generations recorded before projects had a language axis. */
  language: "typescript" | "python" | "go" | null;
  /** Null only for a failed or legacy generation that produced no metadata. */
  meta: GenerationMeta | null;
  warnings: string[];
  /** Present on retrieve and create; omitted in lists. */
  files?: GeneratedFile[];
  error: string | null;
  /** Format: date-time */
  created_at: string;
}

/** A language that did not generate in a multi-language run. */
export interface GenerationFailure {
  language: "typescript" | "python" | "go";
  status: "failed";
  error: string;
}

export interface GenerationBatch {
  data: Array<Generation | GenerationFailure>;
}

export interface ApiKey {
  id: string;
  object: "api_key";
  name: string;
  /** Last four characters of the secret; the secret itself is never stored. */
  last4: string;
  revoked: boolean;
  /** Format: date-time */
  last_used_at: string | null;
  /** Format: date-time */
  created_at: string;
}

export interface UrlSpecRevisionSource {
  kind: "url";
  /** Format: uri */
  url: string;
}

export interface GithubSpecRevisionSource {
  kind: "github";
  /** GitHub repository in owner/name form. */
  repository: string;
  /** Repository-relative specification path. */
  path: string;
  /** Git ref resolved for this revision, when recorded. */
  ref?: string | null;
  /** Exact Git commit consumed, when recorded. */
  commit_sha?: string | null;
}

export type SpecRevisionSource = UrlSpecRevisionSource | GithubSpecRevisionSource;

export interface SpecRevision {
  id: SpecRevisionId;
  object: "spec_revision";
  project_id: ProjectId;
  /** SHA-256 digest of the exact raw specification text. */
  sha256: string;
  /** Size of the raw specification text in bytes. */
  size_bytes: number;
  /** Origin recorded when this immutable revision was created. */
  source: SpecRevisionSource | null;
  /** Format: date-time */
  created_at: string;
}

export interface ProjectList {
  object: ListObject;
  data: Project[];
  /** Whether another page is available after this one. */
  has_more: boolean;
  /** Pass this value as cursor to retrieve the next page; null on the last page. */
  next_cursor: string | null;
}

export interface GenerationList {
  object: ListObject;
  data: Generation[];
  /** Whether another page is available after this one. */
  has_more: boolean;
  /** Pass this value as cursor to retrieve the next page; null on the last page. */
  next_cursor: string | null;
}

export interface SpecRevisionList {
  object: ListObject;
  data: SpecRevision[];
  /** Whether another page is available after this one. */
  has_more: boolean;
  /** Pass this value as cursor to retrieve the next page; null on the last page. */
  next_cursor: string | null;
}

export interface ApiKeyList {
  object: ListObject;
  data: ApiKey[];
  /** Whether another page is available after this one. */
  has_more: boolean;
  /** Pass this value as cursor to retrieve the next page; null on the last page. */
  next_cursor: string | null;
}

export interface DeletedProject {
  id: ProjectId;
  object: "project";
  deleted: true;
}

/** Stable category for deciding how to handle the error. */
export const ErrorType = {
  REQUEST_ERROR: "request_error",
  AUTHENTICATION_ERROR: "authentication_error",
  AUTHORIZATION_ERROR: "authorization_error",
  PLAN_ERROR: "plan_error",
  SOURCE_ERROR: "source_error",
  RATE_LIMIT_ERROR: "rate_limit_error",
  API_ERROR: "api_error",
} as const;
export type ErrorType = (typeof ErrorType)[keyof typeof ErrorType];

/** Stable programmatic identifier. Do not branch on message. */
export const ErrorCode = {
  INVALID_REQUEST: "invalid_request",
  IDEMPOTENCY_KEY_REUSED: "idempotency_key_reused",
  UNAUTHORIZED: "unauthorized",
  ORGANIZATION_REQUIRED: "organization_required",
  NOT_FOUND: "not_found",
  SPEC_ERROR: "spec_error",
  FETCH_ERROR: "fetch_error",
  PLAN_LIMIT_REACHED: "plan_limit_reached",
  PAYLOAD_TOO_LARGE: "payload_too_large",
  RATE_LIMITED: "rate_limited",
  INTERNAL_ERROR: "internal_error",
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ErrorDetail {
  type: ErrorType;
  code: ErrorCode;
  /** JSON Pointer to the invalid request field, when one field caused the error. */
  field?: string;
  /** Human-readable explanation. Its wording may change. */
  message: string;
  /** Whether retrying later can succeed without changing the request. */
  retryable: boolean;
  /** Stable, concise recovery instruction suitable for a person or agent. */
  suggested_action: string;
  /**
   * Documentation for this class of error.
   * Format: uri
   */
  docs_url: string;
}

export interface ErrorModel {
  errors: ErrorDetail[];
  request_id: RequestId;
}
