// typeship — API types.
// Generated by typeship — https://typeship.dev — do not edit by hand.

/** The spec to generate from. Provide exactly one of url or inline. */
export interface SpecInput {
  /** Publicly reachable URL of the spec. Fetched server-side. */
  url?: string;
  /** Raw spec text, JSON or YAML. Up to 10MB. */
  inline?: string;
}

export interface GeneratedFile {
  /** Repo-relative path inside the generated package. */
  path: string;
  content: string;
}

export interface GenerationMeta {
  title: string;
  version: string;
  /** Detected spec version, "2.0", "3.0", or "3.1". */
  oas_version: string;
  /** True when the input was Swagger 2.0 and was converted. */
  converted?: boolean;
  package_name: string;
  client_name: string;
  targets: Array<"sdk" | "cli" | "mcp">;
  resource_count?: number;
  operation_count?: number;
  schema_count?: number;
  paginated_operation_count?: number;
  file_count?: number;
  total_lines?: number;
}

export interface GenerationResult {
  files: GeneratedFile[];
  warnings: string[];
  meta: GenerationMeta;
}

export interface Project {
  id: string;
  object: "project";
  name: string;
  /** Fetched server-side for every generation. */
  spec_url: string;
  targets: Array<"cli" | "mcp">;
  /** Format: date-time */
  created_at: string;
}

export interface Generation {
  id: string;
  object: "generation";
  project_id?: string | null;
  status: "succeeded" | "failed";
  trigger: "manual" | "share" | "webhook";
  meta?: GenerationMeta;
  warnings?: string[];
  /** Present on retrieve and create; omitted in lists. */
  files?: GeneratedFile[];
  error?: string | null;
  /** Format: date-time */
  created_at: string;
}

export interface Share {
  id: string;
  object: "share";
  /** Public path of the share page. Anyone with it can view and download. */
  url: string;
  /** Format: date-time */
  created_at: string;
}

export interface ErrorModel {
  error: {
    code: "invalid_request" | "unauthorized" | "not_found" | "spec_error" | "fetch_error" | "plan_limit_reached" | "payload_too_large";
    message: string;
  };
}
